### ISSUE TITLE
ModuleNotFoundError: No module named 'revChatGPT'

### ISSUE THREAD

**Issue by zuilintan** [RockChinQ/revLibs#1]
```[2023-02-17 02:16:29.529] command.py (161) - [INFO] : [person_XXXXXXXX]发起指令:!reload
[2023-02-17 02:16:29.530] reloader.py (25) - [INFO] : 执行程序关闭流程
[2023-02-17 02:16:29.531] main.py (254) - [INFO] : 持久化session: person_XXXXXXXX
[2023-02-17 02:16:29.547] reloader.py (16) - [INFO] : reload module: audit.gatherer
[2023-02-17 02:16:29.551] reloader.py (16) - [INFO] : reload module: database.manager
[2023-02-17 02:16:29.556] reloader.py (16) - [INFO] : reload module: openai.keymgr
[2023-02-17 02:16:29.557] reloader.py (16) - [INFO] : reload module: openai.manager
[2023-02-17 02:16:29.558] reloader.py (16) - [INFO] : reload module: openai.modelmgr
[2023-02-17 02:16:29.559] reloader.py (16) - [INFO] : reload module: openai.session
[2023-02-17 02:16:29.560] reloader.py (16) - [INFO] : reload module: plugin.host
[2023-02-17 02:16:29.562] reloader.py (16) - [INFO] : reload module: plugin.models
[2023-02-17 02:16:29.562] reloader.py (16) - [INFO] : reload module: plugin.settings
[2023-02-17 02:16:29.563] reloader.py (16) - [INFO] : reload module: plugin.switch
[2023-02-17 02:16:29.564] reloader.py (16) - [INFO] : reload module: qqbot.command
[2023-02-17 02:16:29.565] reloader.py (16) - [INFO] : reload module: qqbot.filter
[2023-02-17 02:16:29.566] reloader.py (16) - [INFO] : reload module: qqbot.manager
[2023-02-17 02:16:29.567] reloader.py (16) - [INFO] : reload module: qqbot.message
[2023-02-17 02:16:29.567] reloader.py (16) - [INFO] : reload module: qqbot.process
[2023-02-17 02:16:29.568] reloader.py (16) - [INFO] : reload module: utils.constants
[2023-02-17 02:16:29.569] reloader.py (16) - [INFO] : reload module: utils.context
[2023-02-17 02:16:29.570] reloader.py (16) - [INFO] : reload module: utils.pkgmgr
[2023-02-17 02:16:29.571] reloader.py (16) - [INFO] : reload module: utils.reloader
[2023-02-17 02:16:29.571] reloader.py (16) - [INFO] : reload module: utils.updater
[2023-02-17 02:16:29.575] reloader.py (16) - [INFO] : reload module: revLibs.main
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/pkg/qqbot/command.py", line 281, in reload_task
    pkg.utils.reloader.reload_all()
  File "/bot/pkg/utils/reloader.py", line 40, in reload_all
    walk(plugins)
  File "/bot/pkg/utils/reloader.py", line 14, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.')
  File "/bot/pkg/utils/reloader.py", line 17, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
  File "/bot/plugins/revLibs/main.py", line 8, in <module>
    from revChatGPT.V1 import Chatbot
ModuleNotFoundError: No module named 'revChatGPT'
```

**Comment by RockChinQ** [comment]
主程序是手动部署的还是自动部署的？自动部署是安装器还是Docker？

**Comment by zuilintan** [comment]
自动部署, Docker

**Comment by RockChinQ** [comment]
依赖库安装失败，可以尝试发送指令`!plugin update`使程序自动解决依赖，或进入容器执行指令`pip3 install revChatGPT --upgrade`

**Comment by zuilintan** [comment]
的确是安装失败, 我将bot/plugins/revLibs删除, 重新
!plugin https://github.com/RockChinQ/revLibs
待其完成后
!reload
这次就正常了

虽然上一次也一样的流程, 但可能过程中网络出现了波动没下全revLibs吧

**Comment by RockChinQ** [comment]
> 的确是安装失败, 我将bot/plugins/revLibs删除, 重新 !plugin https://github.com/RockChinQ/revLibs 待其完成后 !reload 这次就正常了
> 
> 虽然上一次也一样的流程, 但可能过程中网络出现了波动没下全revLibs吧

是的，但可能存在一个异步处理的bug，昨天我也遇到了，解决方案就是重新安装插件

**Comment by nanyansky** [comment]
> 
发送升级命令就报这样的错

Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/pkg/qqbot/command.py", line 121, in closure
    success = updater.pull_latest("/".join(plugin['path'].split('/')[:-1]))
  File "/bot/pkg/utils/updater.py", line 26, in pull_latest
    porcelain.pull(repo)
  File "/usr/local/lib/python3.9/site-packages/dulwich/porcelain.py", line 1261, in pull
    r.reset_index(tree=tree)
  File "/usr/local/lib/python3.9/site-packages/dulwich/repo.py", line 1533, in reset_index
    return build_index_from_tree(
  File "/usr/local/lib/python3.9/site-packages/dulwich/index.py", line 696, in build_index_from_tree
    os.makedirs(os.path.dirname(full_path))
  File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: b''

**Comment by nanyansky** [comment]
> > 的确是安装失败, 我将bot/plugins/revLibs删除, 重新 !plugin https://github.com/RockChinQ/revLibs 待其完成后 !reload 这次就正常了
> > 虽然上一次也一样的流程, 但可能过程中网络出现了波动没下全revLibs吧
> 
> 是的，但可能存在一个异步处理的bug，昨天我也遇到了，解决方案就是重新安装插件


这时我在QQ上得到的机器人的回复：

[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "/bot/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 30, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 100, in get_session
    __sessions__[name] = RevSession(name)
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 34, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "/bot/plugins/revLibs/pkg/process/impls/v1impl.py", line 26, in create_instance
    valid_acc, acc = accmgr.use_account()
  File "/bot/plugins/revLibs/pkg/accounts/accmgr.py", line 56, in use_account
    move_account_to_end(get_account_list()[0])
TypeError: 'set' object is not subscriptable
