### ISSUE TITLE
发送消息就报错：Exception: No login details provided!> 

### ISSUE THREAD

**Issue by d4renk** [RockChinQ/revLibs#10]
```
[2023-02-19 19:50:38.922] main.py (95) - [ERROR] : [rev] Traceback (most recent call last):
  File "/home/app/app/QChatGPT/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 16, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 63, in get_session
    __sessions__[name] = RevSession(name)
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 26, in __init__
    self.__rev_interface_impl__: RevLibInterface = __rev_interface_impl_class__()
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 17, in __init__
    self.chatbot = Chatbot(
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 63, in __init__
    raise Exception("No login details provided!")
Exception: No login details provided!> 
```
是access token登录 国内主机 使用了代理 但一发送消息就报错 
另外在不删除插件情况下 如何停用插件？

**Comment by RockChinQ** [comment]
请截图revcfg.py的内容，注意适当遮住隐私

**Comment by RockChinQ** [comment]
accessToken改为`access_token`

**Comment by RockChinQ** [comment]
请针对每个问题都提供尽量多的信息：控制台输出、聊天记录等
