### ISSUE TITLE
httpx.TooManyRedirects: Exceeded maximum allowed redirects.

### ISSUE THREAD

**Issue by wzh195879702** [RockChinQ/revLibs#100]
我要使用的逆向库是：New Bing
使用指令!plugin update更新到EdgeGPT 0.1.8后出现
Traceback (most recent call last):
  File "/root/QChatGPT/plugins/revLibs/main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 41, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 34, in create_instance
    return EdgeGPTImpl(cookies_dict, revcfg.new_bing_style if hasattr(revcfg, "new_bing_style") else ConversationStyle.balanced), True, cookies_dict
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 38, in __init__
    self.chatbot = Chatbot(cookies=cookies)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 320, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 217, in __init__
    response = self.session.get(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1018, in get
    return self.request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 785, in request
    return self.send(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 871, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 907, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 939, in _send_handling_redirects
    raise TooManyRedirects(
httpx.TooManyRedirects: Exceeded maximum allowed redirects.

**Comment by RockChinQ** [comment]
可能是网络代理过于复杂导致

**Comment by wzh195879702** [comment]
> 可能是网络代理过于复杂导致

可我服务器没开代理，那应该怎么做

**Comment by DefensiveSniper** [comment]
我也一样^^,现在是23年4月6号

**Comment by DefensiveSniper** [comment]
我知道是这个插件的原因，当然不只是acheong08/EdgeGPT，acheong08/ChatGPT.V1也有问题，问题如下
Traceback (most recent call last):
  File "/home/qpt/QChatGPT/plugins/revLibs/main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/qpt/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 58, in process_message
    raise e
  File "/home/qpt/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/home/qpt/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 96, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/home/qpt/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 75, in get_reply
    raise e
  File "/home/qpt/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 55, in get_reply
    for r in reply_gen:
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V1.py", line 453, in ask
    self.__check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V1.py", line 561, in __check_response
    raise error
revChatGPT.typings.Error: OpenAI: Internal Server Error (code: 500)
当然我去openai官网查看了code：500的原因，如下
500 - The server had an error while processing your request. | Cause Issue on our servers.Solution Retry your request after a brief wait and contact us if the issue persists. Read status page.
500 - The server had an error while processing your request.

Cause Issue on our servers.

Solution Retry your request after a brief wait and contact us if the issue persists. Read [status page](https://status.openai.com/).

**Comment by ZerotwoYu** [comment]
pip3 -m EdgeGPT单独运行也会出现此错误，但是设置proxy代理后可以正常使用。之后我修改了EdgeGPTImpl.py里的代码，手动加了proxy参数也不行，估计是我加错地方了。然后我更新了一下httpx模块(pip3 install httpx --upgrade)解决了这个问题。

**Comment by RockChinQ** [comment]
这个报错我也没有办法，因为涉及到了底层依赖或者http相关的网络问题，可以参考上述各种解法，若有其他解法欢迎继续回复；若有涉及本仓库代码的事宜，将会再次开启此issue。
