### ISSUE TITLE
使用中有时会出现下列错误，是ChatGPT接口不稳定吗？yield reply['message'], reply KeyError: 'message'

### ISSUE THREAD

**Issue by wenyinos** [RockChinQ/revLibs#11]
[嘉然Diana]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 83, in process_message
    raise e
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 47, in process_message
    for section in session.get_reply(prompt):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 44, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 54, in get_reply
    yield reply['message'], reply
KeyError: 'message'

另外如何隐藏错误信息，修改QChatGPT/config.py中设置无效。

**Comment by RockChinQ** [comment]
#7

**Comment by RockChinQ** [comment]
逆向库暂不支持隐藏报错信息
