### ISSUE TITLE
NewBing情景模式疑似失效

### ISSUE THREAD

**Issue by wenyinos** [RockChinQ/revLibs#119]
请您认真填写以下信息。

### 任务

- [y] 我已严格按照文档中的步骤操作
- [y] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：（New Bing

### 期望情况

我希望的情况是：

### 实际情况

实际情况是：
```
[2023-04-16 18:35:37.453] main.py (112) - [ERROR] : [rev] Traceback (most recent call last):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 58, in process_message
    raise e
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 96, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 51, in get_reply
    resp = asyncio.run(task)
  File "/home/wenyinos/qcg-bot/python/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/wenyinos/qcg-bot/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/wenyinos/qcg-bot/python/lib/python3.10/site-packages/EdgeGPT.py", line 352, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/home/wenyinos/qcg-bot/python/lib/python3.10/site-packages/EdgeGPT.py", line 294, in ask_stream
    self.request.update(prompt=prompt, conversation_style=conversation_style)
  File "/home/wenyinos/qcg-bot/python/lib/python3.10/site-packages/EdgeGPT.py", line 159, in update
    conversation_style = getattr(ConversationStyle, conversation_style)
  File "/home/wenyinos/qcg-bot/python/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: ConversationStyle.balanced
```

**Comment by RockChinQ** [comment]
尝试重新安装逆向库插件
