### ISSUE TITLE
reload时报错“ModuleNotFoundError: No module named 'revChatGPT’”，windows部署

### ISSUE THREAD

**Issue by BuMing119** [RockChinQ/revLibs#128]
在安装插件后进行reload时遇到以下报错：
“Exception in thread Thread-13 (reload_task):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Qbot-bing\QChatGPT\.\pkg\qqbot\cmds\system\reload.py", line 19, in reload_task
    pkg.utils.reloader.reload_all()
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 49, in reload_all
    walk(plugins)
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 15, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.', path_prefix + item.name + '/')
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 19, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
  File "D:\Qbot-bing\QChatGPT\.\plugins\revLibs\main.py", line 9, in <module>
    from revChatGPT.V1 import Chatbot
ModuleNotFoundError: No module named 'revChatGPT'”

我尝试了这其他帖子里重新安装的方法，但无论是自动安装还是手动安装都还是会出现这个问题。更新插件也试过，也不行。
help！

**Comment by RockChinQ** [comment]
参考这个地方安装revChatGPT库  https://github.com/RockChinQ/qcg-installer/issues/15

pip install后写revChatGPT

**Comment by BuMing119** [comment]
> 参考这个地方安装revChatGPT库 [RockChinQ/qcg-installer#15](https://github.com/RockChinQ/qcg-installer/issues/15)
> 
> pip install后写revChatGPT


Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Qbot-bing\QChatGPT\.\pkg\qqbot\cmds\system\reload.py", line 19, in reload_task
    pkg.utils.reloader.reload_all()
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 49, in reload_all
    walk(plugins)
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 15, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.', path_prefix + item.name + '/')
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 19, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
  File "D:\Qbot-bing\QChatGPT\.\plugins\revLibs\main.py", line 11, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "D:\Qbot-bing\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 4, in <module>
    from plugins.revLibs.pkg.process.impls.edgegpt import EdgeGPTImpl
  File "D:\Qbot-bing\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 9, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
ImportError: cannot import name 'ConversationStyle' from 'EdgeGPT' (D:\Qbot-bing\python\lib\site-packages\EdgeGPT.py)

应该是我以前安装过python环境的原因，我把一些导入的包移动到了项目对应的位置，现在报错成了这个

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Qbot-bing\QChatGPT\.\pkg\qqbot\cmds\system\reload.py", line 19, in reload_task
    pkg.utils.reloader.reload_all()
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 49, in reload_all
    walk(plugins)
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 15, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.', path_prefix + item.name + '/')
  File "D:\Qbot-bing\QChatGPT\.\pkg\utils\reloader.py", line 19, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
  File "D:\Qbot-bing\QChatGPT\.\plugins\revLibs\main.py", line 11, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "D:\Qbot-bing\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 4, in <module>
    from plugins.revLibs.pkg.process.impls.edgegpt import EdgeGPTImpl
  File "D:\Qbot-bing\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 9, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
ImportError: cannot import name 'ConversationStyle' from 'EdgeGPT' (D:\Qbot-bing\python\lib\site-packages\EdgeGPT.py)

**Comment by RockChinQ** [comment]
那你再更新一下这个库`EdgeGPT`
```bash
pip install EdgeGPT --upgrade
```

**Comment by BuMing119** [comment]
> 那你再更新一下这个库`EdgeGPT`
> 
> ```shell
> pip install EdgeGPT --upgrade
> ```

我之前试过这个，但是没有用，我打开EdgeGPT.py看了下，里面并没有ConversationStyle这个类，只有_ConversationStyle

**Comment by BuMing119** [comment]
> [EdgeGPT的](https://github.com/acheong08/EdgeGPT/blob/713ad0f7bb2f8ef1f3245675ac7a9c13cfece6f0/src/EdgeGPT.py#L96)
> 
> 这里有这种类型的，说明你运行程序的环境的EdgeGPT不是最新版本，请找到指定的环境再使用pip更新

现在已经能用了，谢谢。我顺便问一下，new bing能套人格吗（非越狱正常人格），我尝试了一下好像套不了

**Comment by RockChinQ** [comment]
> > [EdgeGPT的](https://github.com/acheong08/EdgeGPT/blob/713ad0f7bb2f8ef1f3245675ac7a9c13cfece6f0/src/EdgeGPT.py#L96)
> > 
> > 这里有这种类型的，说明你运行程序的环境的EdgeGPT不是最新版本，请找到指定的环境再使用pip更新
> 
> 现在已经能用了，谢谢。我顺便问一下，new bing能套人格吗（非越狱正常人格），我尝试了一下好像套不了

正常使用，跟主程序配置方法一样，但是否生效取决于bing
