### ISSUE TITLE
Status code: 400

### ISSUE THREAD

**Issue by NiuHK** [RockChinQ/revLibs#137]
[2023-05-04 21:25:58.955] main.py (112) - [ERROR] : [rev] Traceback (most recent call last):
  File "D:\QQBot\QChatGPT\.\plugins\revLibs\main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "D:\QQBot\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 59, in process_message
    raise e
  File "D:\QQBot\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "D:\QQBot\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 96, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "D:\QQBot\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 54, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "D:\QQBot\python\lib\site-packages\EdgeGPT.py", line 635, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "D:\QQBot\python\lib\site-packages\EdgeGPT.py", line 470, in ask_stream
    raise Exception("Update web page context failed")
Exception: Update web page context failed

**Comment by RockChinQ** [comment]
请使用模板创建issue
