### ISSUE TITLE
Conversation not found（不知原因）

### ISSUE THREAD

**Issue by r5rinimaa** [RockChinQ/revLibs#15]
Field missing
{'detail': 'Conversation not found'}
Traceback (most recent call last):
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 47, in process_message
    for section in session.get_reply(prompt):
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 41, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 54, in get_reply
    yield reply['message'], reply
KeyError: 'message'

**Comment by RockChinQ** [comment]
#7 ,账户请求过多
