### ISSUE TITLE
接入newbing 启动后 回复报错

### ISSUE THREAD

**Issue by mooyume** [RockChinQ/revLibs#186]
请您认真填写以下信息。

### 任务

- [x] 我已严格按照文档中的步骤操作
- [x] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：（例如：New Bing） New Bing

### 期望情况

我希望的情况是：成功接入

### 实际情况

实际情况是： 启动后，给机器人发消息报错，报错如下：
[2023-06-09 00:00:15.106] edgegpt.py (39) - [INFO] : [rev] 初始化NewBing使用代理: None
[2023-06-09 00:00:15.106] edgegpt.py (45) - [INFO] : [rev] 初始化NewBing具有Cookies
[2023-06-09 00:00:16.726] _client.py (1013) - [INFO] : HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
[2023-06-09 00:00:17.171] _client.py (1729) - [INFO] : HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 302 Found"
[2023-06-09 00:00:18.408] _client.py (1729) - [INFO] : HTTP Request: GET https://edge.churchless.tech/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 107, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "E:\QQBOT\python\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
[2023-06-09 00:00:19.562] procmsg.py (54) - [ERROR] : Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 107, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "E:\QQBOT\python\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

[2023-06-09 00:00:19.563] procmsg.py (55) - [WARNING] : 失败，重试(1/3)...
[2023-06-09 00:00:22.066] base_events.py (1752) - [ERROR] : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000029ADA013FD0>
[2023-06-09 00:00:22.066] base_events.py (1752) - [ERROR] : Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000029ADA08CCA0>, 1031984.25)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000029ADA0139D0>
[2023-06-09 00:00:22.067] base_events.py (1752) - [ERROR] : Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000029ADA013D30>
transport: <_ProactorSocketTransport fd=-1 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 690, in _process_write_backlog
  File "asyncio\proactor_events.py", line 365, in write
  File "asyncio\proactor_events.py", line 401, in _loop_writing
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000029AD6518820>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 321, in __del__
  File "asyncio\sslproto.py", line 316, in close
  File "asyncio\sslproto.py", line 599, in _start_shutdown
  File "asyncio\sslproto.py", line 604, in _write_appdata
  File "asyncio\sslproto.py", line 712, in _process_write_backlog
  File "asyncio\sslproto.py", line 726, in _fatal_error
  File "asyncio\proactor_events.py", line 152, in _force_close
  File "asyncio\base_events.py", line 753, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 107, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "E:\QQBOT\python\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
[2023-06-09 00:00:22.269] procmsg.py (54) - [ERROR] : Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 107, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "E:\QQBOT\python\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

[2023-06-09 00:00:22.270] procmsg.py (55) - [WARNING] : 失败，重试(2/3)...
[2023-06-09 00:00:23.101] main.py (270) - [INFO] : QQ: 3607167512, MAH: localhost:8080
[2023-06-09 00:00:23.101] main.py (271) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37
[2023-06-09 00:00:23.101] main.py (285) - [INFO] : 发送赞赏码
[2023-06-09 00:00:23.102] manager.py (387) - [INFO] : 通知管理员:自2022年12月初以来，开发者已经花费了大量时间和精力来维 护本项目，如果您觉得本项目对您有帮助，欢迎赞赏开发者，以支持项目稳定运行😘[图片][图片]BTC: 3N4Azee63vbBB9boGv9Rjf4N5SocMe5eCq
XMR: 89LS21EKQuDGkyQoe2nDupiuWXk4TVD6FALvSKv5owfmeJEPFpHeMsZLYtLiJ6GxLrhsRe5gMs6MyMSDn4GNQAse2Mae4KE

(本消息仅在启动时发送至管理员，如果您不想再看到此消息，请在config.py中将encourage_sponsor_at_start设置为False)
Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 107, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "E:\QQBOT\python\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
[2023-06-09 00:00:25.227] procmsg.py (54) - [ERROR] : Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 107, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "E:\QQBOT\python\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

[2023-06-09 00:00:25.227] procmsg.py (55) - [WARNING] : 失败，重试(3/3)...
Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 107, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "E:\QQBOT\python\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
[2023-06-09 00:00:28.020] main.py (120) - [ERROR] : [rev] Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\main.py", line 113, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 59, in process_message
    raise e
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 107, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "E:\QQBOT\python\lib\site-packages\EdgeGPT\chathub.py", line 85, in ask_stream
    self.wss = await self.wss_session.ws_connect(
  File "E:\QQBOT\python\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

[2023-06-09 00:00:28.021] process.py (161) - [INFO] : 回复[person_342177563]文字消息:[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "E:\QQBOT\QChatGPT\.\plugins\revLibs...
[2023-06-09 00:00:28.026] base_events.py (1752) - [ERROR] : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000029ADA013B80>
[2023-06-09 00:00:28.026] base_events.py (1752) - [ERROR] : Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000029ADA060880>
transport: <_ProactorSocketTransport fd=1112 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 690, in _process_write_backlog
  File "asyncio\proactor_events.py", line 365, in write
  File "asyncio\proactor_events.py", line 401, in _loop_writing
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000029AD6518820>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 321, in __del__
  File "asyncio\sslproto.py", line 316, in close
  File "asyncio\sslproto.py", line 599, in _start_shutdown
  File "asyncio\sslproto.py", line 604, in _write_appdata
  File "asyncio\sslproto.py", line 712, in _process_write_backlog
  File "asyncio\sslproto.py", line 726, in _fatal_error
  File "asyncio\proactor_events.py", line 152, in _force_close
  File "asyncio\base_events.py", line 753, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
[2023-06-09 00:00:28.028] base_events.py (1752) - [ERROR] : Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000029ADA0D3580>, 1031986.953)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000029ADA013BE0>
[2023-06-09 00:00:28.028] base_events.py (1752) - [ERROR] : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000029ADA060460>
[2023-06-09 00:00:28.028] base_events.py (1752) - [ERROR] : Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000029ADA08C700>, 1031989.906)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000029ADA060760>
[2023-06-09 00:00:28.029] base_events.py (1752) - [ERROR] : Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000029ADA060D60>
transport: <_ProactorSocketTransport fd=-1 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 690, in _process_write_backlog
  File "asyncio\proactor_events.py", line 365, in write
  File "asyncio\proactor_events.py", line 401, in _loop_writing
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000029AD6518820>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 321, in __del__
  File "asyncio\sslproto.py", line 316, in close
  File "asyncio\sslproto.py", line 599, in _start_shutdown
  File "asyncio\sslproto.py", line 604, in _write_appdata
  File "asyncio\sslproto.py", line 712, in _process_write_backlog
  File "asyncio\sslproto.py", line 726, in _fatal_error
  File "asyncio\proactor_events.py", line 152, in _force_close
  File "asyncio\base_events.py", line 753, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

**Comment by 957955071** [comment]
一样，我也是这样报错

**Comment by RockChinQ** [comment]
不晓得，感觉是网络不太好，尝试更换境外服务器运行
