### ISSUE TITLE
在安装的时候出现 TypeError: 'type' object is not subscriptable 

### ISSUE THREAD

**Issue by r5rinimaa** [RockChinQ/revLibs#19]
[2023-02-22 05:20:13.769] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/proccmd.py 失败: (<class 'TypeError'>, TypeError("'type' object is not subscriptable"), <traceback object at 0x7feb81159380>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/proccmd.py", line 1, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 3, in <module>
    from plugins.revLibs.pkg.process.impls.v1impl import RevChatGPTV1
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 8, in <module>
    _thr_locks__: dict[str, threading.Lock] = {}
TypeError: 'type' object is not subscriptable

**Comment by r5rinimaa** [comment]
[2023-02-22 05:20:13.766] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/main.py 失败: (<class 'TypeError'>, TypeError("'type' object is not subscriptable"), <traceback object at 0x7feb81144b40>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/main.py", line 10, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 3, in <module>
    from plugins.revLibs.pkg.process.impls.v1impl import RevChatGPTV1
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 8, in <module>
    _thr_locks__: dict[str, threading.Lock] = {}
TypeError: 'type' object is not subscriptable
[2023-02-22 05:20:13.769] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/proccmd.py 失败: (<class 'TypeError'>, TypeError("'type' object is not subscriptable"), <traceback object at 0x7feb81159380>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/proccmd.py", line 1, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 3, in <module>
    from plugins.revLibs.pkg.process.impls.v1impl import RevChatGPTV1
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 8, in <module>
    _thr_locks__: dict[str, threading.Lock] = {}
TypeError: 'type' object is not subscriptable
[2023-02-22 05:20:13.771] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/procmsg.py 失败: (<class 'TypeError'>, TypeError("'type' object is not subscriptable"), <traceback object at 0x7feb81159640>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 2, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 3, in <module>
    from plugins.revLibs.pkg.process.impls.v1impl import RevChatGPTV1
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 8, in <module>
    _thr_locks__: dict[str, threading.Lock] = {}
TypeError: 'type' object is not subscriptable
[2023-02-22 05:20:13.773] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/revss.py 失败: (<class 'TypeError'>, TypeError("'type' object is not subscriptable"), <traceback object at 0x7feb81159680>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 3, in <module>
    from plugins.revLibs.pkg.process.impls.v1impl import RevChatGPTV1
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 8, in <module>
    _thr_locks__: dict[str, threading.Lock] = {}
TypeError: 'type' object is not subscriptable

**Comment by RockChinQ** [comment]
python版本是多少？

**Comment by RockChinQ** [comment]
已经删除这种写法以向下兼容，请到plugins目录删除此插件后重新安装此插件
