### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg.openai.dprompt'

### ISSUE THREAD

**Issue by r5rinimaa** [RockChinQ/revLibs#20]
[2023-02-22 07:36:08.235] host.py (88) - [INFO] : 加载插件
[2023-02-22 07:36:08.242] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/main.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pkg.openai.dprompt'"), <traceback object at 0x7fde739c8ec0>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/main.py", line 10, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 4, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai.dprompt'
[2023-02-22 07:36:08.245] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/proccmd.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pkg.openai.dprompt'"), <traceback object at 0x7fde7314f480>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/proccmd.py", line 1, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 4, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai.dprompt'
[2023-02-22 07:36:08.246] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/procmsg.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pkg.openai.dprompt'"), <traceback object at 0x7fde7314f6c0>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 2, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 4, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai.dprompt'
[2023-02-22 07:36:08.247] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/revss.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pkg.openai.dprompt'"), <traceback object at 0x7fde7314f480>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 4, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai.dprompt'
[2023-02-22 07:36:08.248] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/utils.py 成功
[2023-02-22 07:36:08.249] host.py (80) - [INFO] : 加载模块: plugins/revLibs/revcfg-template.py 成功
[2023-02-22 07:36:08.249] host.py (105) - [INFO] : 初始化插件
2023-02-22 07:36:08 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-22 07:36:08.252] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2023-02-22 07:36:08 - INFO     [WebSocket] 成功登录到账号3540434117。
[2023-02-22 07:36:08.387] websocket.py (194) - [INFO] : [WebSocket] 成功登录到账号3540434117。
2023-02-22 07:36:08 - INFO     [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-02-22 07:36:08.388] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
^CTraceback (most recent call last):
  File "/root/QChatGPT/main.py", line 298, in <module>
    main(True)
  File "/root/QChatGPT/main.py", line 191, in main
    time.sleep(12)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1477, in _shutdown
    lock.acquire()
KeyboardInterrupt: 

root@sever1:~/QChatGPT# pip install openai
Requirement already satisfied: openai in /usr/local/lib/python3.9/dist-packages (0.25.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from openai) (4.64.1)
Requirement already satisfied: openpyxl>=3.0.7 in /usr/local/lib/python3.9/dist-packages (from openai) (3.1.1)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.9/dist-packages (from openai) (2.28.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from openai) (1.24.2)
Requirement already satisfied: pandas>=1.2.3 in /usr/local/lib/python3.9/dist-packages (from openai) (1.5.3)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /usr/local/lib/python3.9/dist-packages (from openai) (1.5.3.230214)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from openai) (4.5.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.9/dist-packages (from openpyxl>=3.0.7->openai) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.2.3->openai) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.2.3->openai) (2022.7.1)
Requirement already satisfied: types-pytz>=2022.1.1 in /usr/local/lib/python3.9/dist-packages (from pandas-stubs>=1.1.0.11->openai) (2022.7.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (3.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (3.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas>=1.2.3->openai) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python -m pip install --upgrade pip
root@sever1:~/QChatGPT# pip install openai --upgrade
Requirement already satisfied: openai in /usr/local/lib/python3.9/dist-packages (0.25.0)
^CERROR: Operation cancelled by user

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python -m pip install --upgrade pip
root@sever1:~/QChatGPT# pip install openai --upgrade
Requirement already satisfied: openai in /usr/local/lib/python3.9/dist-packages (0.25.0)
Collecting openai
  Using cached openai-0.26.5.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.9/dist-packages (from openai) (2.28.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from openai) (4.64.1)
Collecting aiohttp
  Downloading aiohttp-3.8.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 41.7 MB/s eta 0:00:00
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (1.26.14)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (264 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 kB 22.5 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 18.2 MB/s eta 0:00:00
Collecting attrs>=17.3.0
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 13.8 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 20.5 MB/s eta 0:00:00
Building wheels for collected packages: openai
  Building wheel for openai (pyproject.toml) ... done
  Created wheel for openai: filename=openai-0.26.5-py3-none-any.whl size=67596 sha256=227ce1d3e762f439e97f8e94568108133ec41a1da2863e22111827ac72a309f8
  Stored in directory: /root/.cache/pip/wheels/8f/72/d6/0a48b79d1e0c8aaade412dca96449f3eef8b0baf5a4a05ffc4
Successfully built openai
Installing collected packages: multidict, frozenlist, attrs, async-timeout, yarl, aiosignal, aiohttp, openai
  Attempting uninstall: openai
    Found existing installation: openai 0.25.0
    Uninstalling openai-0.25.0:
      Successfully uninstalled openai-0.25.0
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-22.2.0 frozenlist-1.3.3 multidict-6.0.4 openai-0.26.5 yarl-1.8.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python -m pip install --upgrade pip
root@sever1:~/QChatGPT# python3 main.py 
Database initialized.
[2023-02-22 07:37:59.103] keymgr.py (52) - [INFO] : 使用api-key:default
[2023-02-22 07:37:59.172] manager.py (28) - [INFO] : 文字总使用量：1838
[2023-02-22 07:37:59.173] session.py (30) - [INFO] : 加载session: person_2251369488
[2023-02-22 07:37:59.174] manager.py (77) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790]
[2023-02-22 07:37:59.175] host.py (88) - [INFO] : 加载插件
[2023-02-22 07:37:59.181] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/main.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pkg.openai.dprompt'"), <traceback object at 0x7ff28bf01dc0>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/main.py", line 10, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 4, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai.dprompt'
[2023-02-22 07:37:59.185] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/proccmd.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pkg.openai.dprompt'"), <traceback object at 0x7ff28bf14540>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/proccmd.py", line 1, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 4, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai.dprompt'
[2023-02-22 07:37:59.187] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/procmsg.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pkg.openai.dprompt'"), <traceback object at 0x7ff28bf14880>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 2, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 4, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai.dprompt'
[2023-02-22 07:37:59.189] host.py (82) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/revss.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pkg.openai.dprompt'"), <traceback object at 0x7ff28bf14700>)
Traceback (most recent call last):
  File "/root/QChatGPT/pkg/plugin/host.py", line 79, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 4, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai.dprompt'

**Comment by RockChinQ** [comment]
> 我来回答这个问题吧，因为我也出现了并且解决了，我出现这个后寻找报错的源代码发现引用的python文件不存在，该文件是切换情景预设的功能，其主要效果是支持情景切换，知道这一点后有两种解决方法。
> 1. 使用！update 更新终点，以添加新的情景切换功能，从而自动生成python文件
> 2. 删除原代码文件里的import，并删减掉所有引用情景切换的功能函数

是的，这是一个版本兼容问题，建议使用方法1更新主程序
