### ISSUE TITLE
【New Bing】websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200

### ISSUE THREAD

**Issue by tian1326** [RockChinQ/revLibs#213]
### 预期/正在使用的逆向库

我要使用的逆向库是：New Bing（例如：New Bing）

### 期望情况

我希望的情况是：机器人可以正常回应

### 实际情况

实际情况是：报出错误：websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200
应该不是代理的问题，我配置的是全局代理，clash中可以看到连接记录，且用浏览器同个节点可以用bing，cookie已经更换
以下是详细日志（从开始到报错）
```[2023-07-10 17:25:36.464] main.py (73) - [INFO] : 检查config模块完整性.
[2023-07-10 17:25:36.465] main.py (101) - [INFO] : 检查tips模块完整性.
Database initialized.
[2023-07-10 17:25:36.892] keymgr.py (61) - [INFO] : 使用api-key:default
[2023-07-10 17:25:36.892] manager.py (30) - [INFO] : 文字总使用量：0
[2023-07-10 17:25:36.892] session.py (67) - [INFO] : 加载session: person_12312413
[2023-07-10 17:25:36.893] manager.py (121) - [INFO] : Use adapter:nakuru
[2023-07-10 17:25:36.958] manager.py (246) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-07-10 17:25:36.958] host.py (91) - [INFO] : 加载插件
[2023-07-10 17:25:36.959] models.py (219) - [INFO] : 插件注册完成: n='Switcher', d='快捷切换使用的模型', v=0.1.1, a='RockChinQ' (<class 'plugins.Switcher.main.SwitcherPlugin'>)
[2023-07-10 17:25:36.968] models.py (219) - [INFO] : 插件注册完成: n='SysStat', d='查看系统状态', v=0.1, a='RockChinQ' (<class 'plugins.SysStatPlugin.main.SysStatPlugin'>)
[2023-07-10 17:25:36.988] vits_text_to_speech.py (17) - [WARNING] : model文件夹中没有模型或配置文件，vits不会启动
[2023-07-10 17:25:37.032] models.py (219) - [INFO] : 插件注册完成: n='chat_voice', d='让机器人用语音输出', v=0.7, a='oliverkirk-sudo' (<class 'plugins.chat_voice.main.ChatVoicePlugin'>)
/home/tian1326/.local/lib/python3.9/site-packages/revChatGPT/__init__.py:31: UserWarning: The current Python is not a recommended version, 3.10+ is recommended
  __import__("warnings").warn(
[2023-07-10 17:25:37.237] models.py (219) - [INFO] : 插件注册完成: n='revLibs', d='接入acheong08/ChatGPT等逆向库', v=0.7.2, a='RockChinQ' (<class 'plugins.revLibs.main.RevLibsPlugin'>)
[2023-07-10 17:25:37.239] host.py (108) - [INFO] : 初始化插件
[2023-07-10 17:25:37.239] host.py (116) - [INFO] : 插件 chat_voice 已初始化
[2023-07-10 17:25:37.239] main.py (82) - [INFO] : [rev] 已加载逆向库acheong08/EdgeGPT, 使用接口实现类: <class 'plugins.revLibs.pkg.process.impls.edgegpt.EdgeGPTImpl'>
[2023-07-10 17:25:37.240] main.py (106) - [INFO] : [rev] 已将主程序消息处理超时时间设置为10分钟
[2023-07-10 17:25:37.240] host.py (116) - [INFO] : 插件 revLibs 已初始化
[2023-07-10 17:25:37.240] host.py (116) - [INFO] : 插件 Switcher 已初始化
[2023-07-10 17:25:37.240] host.py (116) - [INFO] : 插件 SysStat 已初始化
[2023-07-10 17:25:37.240] main.py (212) - [INFO] : 使用账号: 1233454434
[2023-07-10 17:25:37.243] application.py (59) - [INFO] : Protocol: connected
[2023-07-10 17:25:49.253] main.py (286) - [INFO] : host: 172.17.0.1, port: 6700, http_port: 5700
[2023-07-10 17:25:49.253] main.py (287) - [CRITICAL] : 程序启动完成,如长时间未显示 "Protocol: connected" ,并且不回复消息,请检查config.py中的nakuru_config是否正确
[2023-07-10 17:25:54.982] main.py (316) - [INFO] : 当前已是最新版本
[2023-07-10 17:26:19.175] application.py (95) - [INFO] : Event: handling a event: FriendMessage
[2023-07-10 17:26:19.176] procmsg.py (19) - [INFO] : [rev] 收到person_213231413消息: 你知道bing是什么吗？
[2023-07-10 17:26:19.176] edgegpt.py (39) - [INFO] : [rev] 初始化NewBing使用代理: None
[2023-07-10 17:26:19.176] edgegpt.py (45) - [INFO] : [rev] 初始化NewBing具有Cookies
[2023-07-10 17:26:19.900] _client.py (1013) - [INFO] : HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
[2023-07-10 17:26:20.735] _client.py (1729) - [INFO] : HTTP Request: GET https://www.bing.com/turing/conversation/create "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/home/tian1326/qchat/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/home/tian1326/qchat/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/home/tian1326/qchat/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/tian1326/.local/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/home/tian1326/.local/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 102, in ask_stream
    async with connect(
  File "/home/tian1326/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 642, in __aenter__
    return await self
  File "/home/tian1326/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/tian1326/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/home/tian1326/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200
[2023-07-10 17:26:21.921] procmsg.py (63) - [ERROR] : Traceback (most recent call last):
  File "/home/tian1326/qchat/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/home/tian1326/qchat/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/home/tian1326/qchat/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/tian1326/.local/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/home/tian1326/.local/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 102, in ask_stream
    async with connect(
  File "/home/tian1326/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 642, in __aenter__
    return await self
  File "/home/tian1326/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/tian1326/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/home/tian1326/.local/lib/python3.9/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200
```

**Comment by tian1326** [comment]
忘记去EdgeGPT的仓库看了，这是EdgeGPT的问题解决方案使用旧版EdgeGPT，
`python -m pip install EdgeGPT==0.10.16`
