### ISSUE TITLE
[ERROR] : [rev] Traceback (most recent call last)

### ISSUE THREAD

**Issue by BA4413** [RockChinQ/revLibs#225]
[2023-08-18 09:22:35.405] procmsg.py (19) - [INFO] : [rev] 收到person_**********消息: 你好
[2023-08-18 09:22:37.258] main.py (168) - [ERROR] : [rev] Traceback (most recent call last):
  File "E:\ITool\qq\QChatGPT\.\plugins\revLibs\main.py", line 136, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "E:\ITool\qq\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "E:\ITool\qq\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 149, in get_session
    __sessions__[name] = RevSession(name)
  File "E:\ITool\qq\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 62, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "E:\ITool\qq\QChatGPT\.\plugins\revLibs\pkg\process\impls\claude.py", line 36, in create_instance
    return ClaudeImpl(cookies), True, cookies_list
  File "E:\ITool\qq\QChatGPT\.\plugins\revLibs\pkg\process\impls\claude.py", line 39, in __init__
    self.chatbot = Client(cookies)
  File "E:\ITool\qq\python\lib\site-packages\claude_api.py", line 13, in __init__
  File "E:\ITool\qq\python\lib\site-packages\claude_api.py", line 32, in get_organization_id
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)

[2023-08-18 09:22:37.259] process.py (161) - [INFO] : 回复[person_********]文字消息:[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "E:\ITool\qq\QChatGPT\.\plugins\revL...

**Comment by RockChinQ** [comment]
尝试更新一下 `claude-api`库
