### ISSUE TITLE
ca证书的错误？

### ISSUE THREAD

**Issue by baidusima** [RockChinQ/revLibs#226]
请您认真填写以下信息。

### 任务

- [x] 我已严格按照文档中的步骤操作
- [x] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：claude

### 期望情况

我希望的情况是

### 实际情况

实际情况是：[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\curl_cffi\requests\session.py", line 436, in request
    c.perform()
  File "C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\curl_cffi\curl.py", line 191, in perform
    self._check_error(ret, action="perform")
  File "C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\curl_cffi\curl.py", line 84, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\curl_cffi\cacert.pem CApath: none'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\31447\Desktop\新建文件夹\QChatGPT\.\plugins\revLibs\main.py", line 136, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\31447\Desktop\新建文件夹\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\31447\Desktop\新建文件夹\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 149, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\31447\Desktop\新建文件夹\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 62, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "C:\Users\31447\Desktop\新建文件夹\QChatGPT\.\plugins\revLibs\pkg\process\impls\claude.py", line 36, in create_instance
    return ClaudeImpl(cookies), True, cookies_list
  File "C:\Users\31447\Desktop\新建文件夹\QChatGPT\.\plugins\revLibs\pkg\process\impls\claude.py", line 39, in __init__
    self.chatbot = Client(cookies)
  File "C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\claude_api.py", line 13, in __init__
    self.organization_id = self.get_organization_id()
  File "C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\claude_api.py", line 31, in get_organization_id
    response = requests.get(url, headers=headers,impersonate="chrome110")
  File "C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\curl_cffi\requests\__init__.py", line 46, in request
    return s.request(
  File "C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\curl_cffi\requests\session.py", line 438, in request
    raise RequestsError(e)
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\31447\Desktop\新建文件夹\python\lib\site-packages\curl_cffi\cacert.pem CApath: none'

**Comment by RockChinQ** [comment]
这个是逆向库层面的问题，请前往 https://github.com/KoushikNavuluri/Claude-API 的issues查找解决办法

**Comment by baidusima** [comment]
不止Claude会出错newbing也是[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
&nbsp; File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\main.py", line 136, in normal_message_received
&nbsp; &nbsp; reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
&nbsp; File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 32, in process_message
&nbsp; &nbsp; session: revss.RevSession = revss.get_session(session_name)
&nbsp; File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 149, in get_session
&nbsp; &nbsp; __sessions__[name] = RevSession(name)
&nbsp; File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 55, in __init__
&nbsp; &nbsp; self.reset()
&nbsp; File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 128, in reset
&nbsp; &nbsp; self.__rev_interface_impl__.reset_chat()
&nbsp; File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 105, in reset_chat
&nbsp; &nbsp; asyncio.run(self.chatbot.reset())
&nbsp; File "asyncio\runners.py", line 44, in run
&nbsp; File "asyncio\base_events.py", line 649, in run_until_complete
&nbsp; File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\EdgeGPT\EdgeGPT.py", line 228, in reset
&nbsp; &nbsp; await Conversation.create(self.proxy, cookies=self.chat_hub.cookies),
&nbsp; File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\EdgeGPT\conversation.py", line 112, in create
&nbsp; &nbsp; raise Exception("Authentication failed")
Exception: Authentication failed






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RockChinQ/revLibs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RockChinQ/revLibs] ca证书的错误？ (Issue #226)





 
这个是逆向库层面的问题，请前往 https://github.com/KoushikNavuluri/Claude-API 的issues查找解决办法

**Comment by RockChinQ** [comment]
newbing现在已不可用
