### ISSUE TITLE
hugchat 逆向库报错

### ISSUE THREAD

**Issue by DODOTAX** [RockChinQ/revLibs#229]
- [√] 我已严格按照文档中的步骤操作
- [√] 我已经搜索了相关的issue

我要使用的逆向库是：hugchat

Issue好像没找到有类似的问题

实际情况是：
[2023-09-29 23:24:49.191] main.py (145) - [ERROR] : [rev] Traceback (most recent call last):
  File "D:\Chatgpt\QChatgpt\python\lib\site-packages\hugchat\hugchat.py", line 373, in chat
    obj = json.loads(res[5:])
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Chatgpt\QChatgpt\QChatGPT\.\plugins\revLibs\main.py", line 113, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "D:\Chatgpt\QChatgpt\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 68, in process_message
    raise e
  File "D:\Chatgpt\QChatgpt\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "D:\Chatgpt\QChatgpt\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 118, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "D:\Chatgpt\QChatgpt\QChatGPT\.\plugins\revLibs\pkg\process\impls\hugchat.py", line 38, in get_reply
    resp = self.chatbot.chat(prompt)
  File "D:\Chatgpt\QChatgpt\python\lib\site-packages\hugchat\hugchat.py", line 377, in chat
    raise ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"type":"status","status":"started"}

**Comment by RockChinQ** [comment]
请到 github.com/Soulter/hugging-chat-api 寻求帮助
