### ISSUE TITLE
配置完毕重启主程序后，插件列表为空

### ISSUE THREAD

**Issue by MZerg** [RockChinQ/revLibs#23]
手动修改启用插件的配置文件后重载提示：
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/pkg/qqbot/command.py", line 309, in reload_task
    pkg.utils.reloader.reload_all()
  File "/bot/pkg/utils/reloader.py", line 40, in reload_all
    walk(plugins)
  File "/bot/pkg/utils/reloader.py", line 14, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.')
  File "/bot/pkg/utils/reloader.py", line 17, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
  File "/bot/plugins/revLibs/main.py", line 8, in <module>
    from revChatGPT.V1 import Chatbot
ModuleNotFoundError: No module named 'revChatGPT'

**Comment by RockChinQ** [comment]
#1
