### ISSUE TITLE
报错KeyError: 'message'

### ISSUE THREAD

**Issue by Vanda688** [RockChinQ/revLibs#230]
报错信息：
KeyError: 'message'
[2023-10-24 16:57:28.462] main.py (149) - [ERROR] : [rev] Traceback (most recent call last):
  File "/root/bot/QChatGPT/plugins/revLibs/main.py", line 117, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/root/bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 68, in process_message
    raise e
  File "/root/bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/root/bot/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 118, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/root/bot/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 130, in get_reply
    raise e
  File "/root/bot/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 87, in get_reply
    is_func_call, func_name, args = fp.extra_function_call(reply['message'])
KeyError: 'message'

**Comment by RockChinQ** [comment]
revChatGPT貌似挂了，可以试试其他的来源

**Comment by Vanda688** [comment]
OK，感谢大佬🙏
