### ISSUE TITLE
"No module named 'g4f.Provider.NoowAi'"

### ISSUE THREAD

**Issue by HoshinoHikariNeko** [RockChinQ/revLibs#232]
请您认真填写以下信息。

### 任务

我已严格按照文档中的步骤操作
我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：Claude 2

### 期望情况

我希望的情况是：插件正常部署运行

### 实际情况

实际情况是：在!reload后插件导入依赖报错

系统 windows 10 专业版 python版本 3.11.4 QChatGPT版本 2.6.6
依赖报错后我自己重新加载了一次依赖 没成功 同一个报错
报错信息大致如下
C:\Users\ZERO-VOID\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\ZERO-VOID\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
C:\Users\ZERO-VOID\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
[2023-12-18 10:26:27.544] _client.py (1729) - [INFO] : HTTP Request: GET http://localhost:8080/countMessage "HTTP/1.1 200 OK"
Exception in thread Thread-9 (reload_task):
Traceback (most recent call last):
  File "C:\Users\ZERO-VOID\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\ZERO-VOID\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ZERO-VOID\Desktop\project\QChatGPT GPT-4-Shizuku\pkg\qqbot\cmds\system\reload.py", line 21, in reload_task
    pkg.utils.reloader.reload_all()
  File "C:\Users\ZERO-VOID\Desktop\project\QChatGPT GPT-4-Shizuku\pkg\utils\reloader.py", line 48, in reload_all
    walk(plugins)
  File "C:\Users\ZERO-VOID\Desktop\project\QChatGPT GPT-4-Shizuku\pkg\utils\reloader.py", line 14, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.', path_prefix + item.name + '/')
  File "C:\Users\ZERO-VOID\Desktop\project\QChatGPT GPT-4-Shizuku\pkg\utils\reloader.py", line 18, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZERO-VOID\Desktop\project\QChatGPT GPT-4-Shizuku\plugins\revLibs\main.py", line 13, in <module>
    import plugins.revLibs.pkg.process.proccmd as proccmd
  File "C:\Users\ZERO-VOID\Desktop\project\QChatGPT GPT-4-Shizuku\plugins\revLibs\pkg\process\proccmd.py", line 4, in <module>
    import plugins.revLibs.pkg.process.impls.gpt4free as gpt4free
  File "C:\Users\ZERO-VOID\Desktop\project\QChatGPT GPT-4-Shizuku\plugins\revLibs\pkg\process\impls\gpt4free.py", line 6, in <module>
    import g4f
  File "C:\Users\ZERO-VOID\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\__init__.py", line 6, in <module>
    from .models   import Model, ModelUtils, _all_models
  File "C:\Users\ZERO-VOID\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\models.py", line 4, in <module>
    from .Provider   import BaseProvider, RetryProvider
  File "C:\Users\ZERO-VOID\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\__init__.py", line 42, in <module>
    from .NoowAi          import NoowAi
ModuleNotFoundError: No module named 'g4f.Provider.NoowAi'

**Comment by RockChinQ** [comment]
确定是要所有claude吗？这个报错是gpt4free的报错。你看看你revcfg.py指定的使用是哪个逆向工程库

**Comment by HoshinoHikariNeko** [comment]
> 确定是要使用claude吗？这个报错是gpt4free的报错。你看看你revcfg.py指定的使用是哪个逆向工程库
部署阶段没成功revcfg没生成出来所以说还没来得及配置...

**Comment by CakeZH** [comment]
有同样的问题，因为报错所以生成不了revcfg文件

**Comment by RockChinQ** [comment]
gpt4free 0.1.9.4 版本的问题，已经不是第一次出现类似的疏忽问题了。目前在 `requirements.txt` 中限制了`g4f==0.1.9.3`，而不使用 v0.1.9.4的gpt4free 版本。现在遇到这个问题，可以先删除 `plugins`目录下的`revLibs`目录，再重新安装此插件解决。
