### ISSUE TITLE
未生成revcfg.py文件; No module named 'pkg.openai'

### ISSUE THREAD

**Issue by ghost** [RockChinQ/revLibs#235]
请您认真填写以下信息。

### 任务

- [x] 我已严格按照文档中的步骤操作
- [x] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：未开始使用（例如：New Bing）

### 期望情况

我希望的情况是：

### 实际情况

实际情况是：

python .\main.py
执行主程序后报错, 根目录未生成revcfg.py文件

```
PS C:\Users\xc9\Desktop\DMZ\QChatGPT> python .\main.py

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

[2024-02-26 10:59:30.267] C:\Users\xc9\Desktop\DMZ\QChatGPT\pkg\platform\manager.py (108) - [INFO] :
    初始化平台适配器 0: nakuru
[2024-02-26 10:59:30.759] C:\Users\xc9\Desktop\DMZ\QChatGPT\pkg\plugin\loaders\legacy.py (147) - [ERROR] :
    加载插件模块 revLibs.main 时发生错误
Traceback (most recent call last):
  File "C:\Users\xc9\Desktop\DMZ\QChatGPT\pkg\plugin\loaders\legacy.py", line 141, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "C:\Users\xc9\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xc9\Desktop\DMZ\QChatGPT\plugins\revLibs\main.py", line 11, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "C:\Users\xc9\Desktop\DMZ\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 9, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai'
```

**Comment by RockChinQ** [comment]
兼容性问题，请等待修复

**Comment by Sirayn** [comment]
我也有相同问题.
等修复...

**Comment by ikun-mr** [comment]
已经12月了
然而还是没修

**Comment by RockChinQ** [comment]
revLibs只支持2.x。

都别搞了，国产那些厂商价格基本等于白送了。别再搞逆向了，逆向没有前途的。
