### ISSUE TITLE
请问一下，我安装文件后，根目录未生成文件claude.json

### ISSUE THREAD

**Issue by zhi-yao-ai** [RockChinQ/revLibs#236]
请您认真填写以下信息。

### 任务

- [√ ] 我已严格按照文档中的步骤操作
- [ ]√ 我已经搜索了相关的issue

### 预期/正在使用的逆向库 Chat3.5

我要使用的逆向库是：（例如：Claude）

### 期望情况

我希望的情况是：

### 实际情况

实际情况是：
根目录未生成文件claude.json 我无法填入Claude的Cookies

[2024-03-02 14:50:13.925] claude.py (23) - [ERROR] : Claude cookies不存在
[2024-03-02 14:50:13.927] main.py (141) - [ERROR] : [rev] Traceback (most recent call last):
  File "D:\zawu\ruanjian\jiqi\qqbot\QChatGPT\plugins\revLibs\main.py", line 109, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "D:\zawu\ruanjian\jiqi\qqbot\QChatGPT\plugins\revLibs\pkg\process\procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "D:\zawu\ruanjian\jiqi\qqbot\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 154, in get_session
    __sessions__[name] = RevSession(name)
  File "D:\zawu\ruanjian\jiqi\qqbot\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 49, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "D:\zawu\ruanjian\jiqi\qqbot\QChatGPT\plugins\revLibs\pkg\process\impls\claude.py", line 24, in create_instance
    raise Exception("Claude cookies不存在, 请根据文档进行配置: https://github.com/RockChinQ/revLibs")
Exception: Claude cookies不存在, 请根据文档进行配置: https://github.com/RockChinQ/revLibs

**Comment by RockChinQ** [comment]
要你自己创建这个文件然后粘贴cookies进去

**Comment by zhi-yao-ai** [comment]
> 要你自己创建这个文件然后粘贴cookies进去

请问如何创建呢，我自己创建一个同名的记事本就可以么，我并没有找到相关的文件

**Comment by zhi-yao-ai** [comment]
> 要你自己创建这个文件然后粘贴cookies进去



> 要你自己创建这个文件然后粘贴cookies进去

请问是需要一定的相关知识来进行创建？
