### ISSUE TITLE
git结束后!reload [bot] 未知命令: reload 重启docker后提示导入名为 pkg.openai 的模块时失败

### ISSUE THREAD

**Issue by Wang-Nainai** [RockChinQ/revLibs#240]
我已严格按照文档中的步骤操作  我已经搜索了相关的issue

我要使用的逆向库是：gpt4free

实际情况是：运行!plugin get https://github.com/RockChinQ/revLibs 后尝试使用 !reload 命令来重载插件，但系统提示“未知命令: reload”。 重启docker后提示 提示导入错误：当您尝试加载 RevLib Support for QChatGPT 插件时，报告了 ModuleNotFoundError: No module named 'pkg.openai' 错误。可能 Python 在尝试导入名为 pkg.openai 的模块时失败了

运行的环境是黑群晖7.1.2 docker ———————————————————————————————————————————————————————
部署： WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.警告：以 'root' 用户身份运行 pip 可能会导致权限中断以及与系统包管理器发生冲突的行为，从而可能导致您的系统不可用。建议改用虚拟环境：[https://pip.pypa.io/warnings/venv。如果您知道自己在做什么并希望禁止显示此警告，请使用](https://pip.pypa.io/warnings/venv%E3%80%82%E5%A6%82%E6%9E%9C%E6%82%A8%E7%9F%A5%E9%81%93%E8%87%AA%E5%B7%B1%E5%9C%A8%E5%81%9A%E4%BB%80%E4%B9%88%E5%B9%B6%E5%B8%8C%E6%9C%9B%E7%A6%81%E6%AD%A2%E6%98%BE%E7%A4%BA%E6%AD%A4%E8%AD%A6%E5%91%8A%EF%BC%8C%E8%AF%B7%E4%BD%BF%E7%94%A8) --root-user-action 选项。 [2024-10-14 05:06:52.593] /app/pkg/pipeline/process/handlers/command.py (112) - [INFO] :[2024-10-14 05：06：52.593] /app/pkg/pipeline/process/handlers/command.py （112） - [信息] ： 命令返回: 插件安装成功，请重启程序以加载插件 命令返回: 插件安装成功，请重启程序以加载插件 [2024-10-14 05:07:13.863] /app/pkg/pipeline/process/process.py (42) - [INFO] :[2024-10-14 05：07：13.863] /app/pkg/pipeline/process/process.py （42） - [信息] ： 处理 person_2833632558 的请求(1): ！reload处理 person_2833632558 的请求(1): ！ reload 处理 person_2833632558 的请求(1): ！reload处理 person_2833632558 的请求(1): ！ reload [2024-10-14 05:07:13.866] /app/pkg/pipeline/process/handlers/command.py (85) - [INFO] :[2024-10-14 05：07：13.866] /app/pkg/pipeline/process/handlers/command.py （85） - [信息] ： 命令(1)报错: 未知命令: reload 命令(1)报错: 未知命令: reload
——————————————————————————————————————————————————————
重启后：
[2024-10-14 05:18:21.136] /app/pkg/plugin/loaders/classic.py (195) - [ERROR] :
[2024-10-14 05：18：21.136] /app/pkg/plugin/loaders/classic.py （195） - [错误] ：
加载插件模块 revLibs.main 时发生错误
Traceback (most recent call last):
回溯 （最近调用最后）：
File "/app/pkg/plugin/loaders/classic.py", line 189, in _walk_plugin_path
文件 “/app/pkg/plugin/loaders/classic.py”，第 189 行，_walk_plugin_path
importlib.import_module(module.name + "." + item.name)
importlib.import_module（模块。名称 + “.” + item.name）
File "/usr/local/lib/python3.10/importlib/init.py", line 126, in import_module
文件 “/usr/local/lib/python3.10/importlib/init.py”，第 126 行，import_module
return _bootstrap._gcd_import(name[level:], package, level)
返回 _bootstrap._gcd_import（name[level：]， package， level）
File "", line 1050, in _gcd_import
文件 “”，第 1050 行，_gcd_import
File "", line 1027, in _find_and_load
文件 “”，第 1027 行，_find_and_load
File "", line 1006, in _find_and_load_unlocked
文件 “”，第 1006 行，_find_and_load_unlocked
File "", line 688, in _load_unlocked
文件 “”，第 688 行，_load_unlocked
File "", line 883, in exec_module
文件 “”，第 883 行，exec_module
File "", line 241, in _call_with_frames_removed
文件 “”，第 241 行，_call_with_frames_removed
File "/app/plugins/revLibs/main.py", line 11, in
文件 “/app/plugins/revLibs/main.py”，第 11 行，在
import plugins.revLibs.pkg.process.revss as revss
将 plugins.revLibs.pkg.process.revss 导入为 Revss
File "/app/plugins/revLibs/pkg/process/revss.py", line 9, in
文件 “/app/plugins/revLibs/pkg/process/revss.py”，第 9 行，在
import pkg.openai.dprompt as dprompt
将 pkg.openai.dprompt 导入为 dprompt
ModuleNotFoundError: No module named 'pkg.openai'
ModuleNotFoundError：没有名为“pkg.openai”的模块
[2024-10-14 05:18:21.730] /app/pkg/plugin/loaders/classic.py (195) - [ERROR] :
[2024-10-14 05：18：21.730] /app/pkg/plugin/loaders/classic.py （195） - [错误] ：
加载插件模块 revLibs.pkg.process.proccmd 时发生错误
Traceback (most recent call last):
回溯 （最近调用最后）：
File "/app/pkg/plugin/loaders/classic.py", line 189, in _walk_plugin_path
文件 “/app/pkg/plugin/loaders/classic.py”，第 189 行，_walk_plugin_path
importlib.import_module(module.name + "." + item.name)
importlib.import_module（模块。名称 + “.” + item.name）
File "/usr/local/lib/python3.10/importlib/init.py", line 126, in import_module
文件 “/usr/local/lib/python3.10/importlib/init.py”，第 126 行，import_module
return _bootstrap._gcd_import(name[level:], package, level)
返回 _bootstrap._gcd_import（name[level：]， package， level）
File "", line 1050, in _gcd_import
文件 “”，第 1050 行，_gcd_import
File "", line 1027, in _find_and_load
文件 “”，第 1027 行，_find_and_load
File "", line 1006, in _find_and_load_unlocked
文件 “”，第 1006 行，_find_and_load_unlocked
File "", line 688, in _load_unlocked
文件 “”，第 688 行，_load_unlocked
File "", line 883, in exec_module
文件 “”，第 883 行，exec_module
File "", line 241, in _call_with_frames_removed
文件 “”，第 241 行，_call_with_frames_removed
File "/app/plugins/revLibs/pkg/process/proccmd.py", line 1, in
文件 “/app/plugins/revLibs/pkg/process/proccmd.py”，第 1 行，在
import plugins.revLibs.pkg.process.revss as revss
将 plugins.revLibs.pkg.process.revss 导入为 Revss
File "/app/plugins/revLibs/pkg/process/revss.py", line 9, in
文件 “/app/plugins/revLibs/pkg/process/revss.py”，第 9 行，在
import pkg.openai.dprompt as dprompt
将 pkg.openai.dprompt 导入为 dprompt
ModuleNotFoundError: No module named 'pkg.openai'
ModuleNotFoundError：没有名为“pkg.openai”的模块

**Comment by Wang-Nainai** [comment]
> 我已严格按照文档中的步骤操作 我已经搜索了相关的issue
> 
> 我要使用的逆向库是：gpt4free
> 
> 实际情况是：运行!plugin get https://github.com/RockChinQ/revLibs 后尝试使用 !reload 命令来重载插件，但系统提示“未知命令: reload”。 重启docker后提示 提示导入错误：当您尝试加载 RevLib Support for QChatGPT 插件时，报告了 ModuleNotFoundError: No module named 'pkg.openai' 错误。可能 Python 在尝试导入名为 pkg.openai 的模块时失败了
> 
> 运行的环境是黑群晖7.1.2 docker ——————————————————————————————————————————————————————— 
部署： WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.警告：以 'root' 用户身份运行 pip 可能会导致权限中断以及与系统包管理器发生冲突的行为，从而可能导致您的系统不可用。建议改用虚拟环境：https://pip.pypa.io/warnings/venv。如果您知道自己在做什么并希望禁止显示此警告，请使用 --root-user-action 选项。 [2024-10-14 05:06:52.593] /app/pkg/pipeline/process/handlers/command.py (112) - [INFO] :[2024-10-14 05：06：52.593] /app/pkg/pipeline/process/handlers/command.py （112） - [信息] ： 命令返回: 插件安装成功，请重启程序以加载插件 命令返回: 插件安装成功，请重启程序以加载插件 [2024-10-14 05:07:13.863] /app/pkg/pipeline/process/process.py (42) - [INFO] :[2024-10-14 05：07：13.863] /app/pkg/pipeline/process/process.py （42） - [信息] ： 处理 person_2833632558 的请求(1): ！reload处理 person_2833632558 的请求(1): ！ reload 处理 person_2833632558 的请求(1): ！reload处理 person_2833632558 的请求(1): ！ reload [2024-10-14 05:07:13.866] /app/pkg/pipeline/process/handlers/command.py (85) - [INFO] :[2024-10-14 05：07：13.866] /app/pkg/pipeline/process/handlers/command.py （85） - [信息] ： 命令(1)报错: 未知命令: reload 命令(1)报错: 未知命令: reload
>——————————————————————————————————————————————————————
> 重启后：
[2024-10-14 05:18:21.136] /app/pkg/plugin/loaders/classic.py (195) - [ERROR] :
    加载插件模块 revLibs.main 时发生错误
Traceback (most recent call last):
  File "/app/pkg/plugin/loaders/classic.py", line 189, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/plugins/revLibs/main.py", line 11, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/app/plugins/revLibs/pkg/process/revss.py", line 9, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai'
[2024-10-14 05:18:21.730] /app/pkg/plugin/loaders/classic.py (195) - [ERROR] :
    加载插件模块 revLibs.pkg.process.proccmd 时发生错误
Traceback (most recent call last):
  File "/app/pkg/plugin/loaders/classic.py", line 189, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/plugins/revLibs/pkg/process/proccmd.py", line 1, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "/app/plugins/revLibs/pkg/process/revss.py", line 9, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai'
