### ISSUE TITLE
revChatGPT.V1.Error   逆向库报错

### ISSUE THREAD

**Issue by kirara233** [RockChinQ/revLibs#25]
下附错误代码

[2023-02-22 22:46:48.439] main.py (95) - [ERROR] : [rev] Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QQbot+VITS\QQbot\bot\QChatGPT\.\plugins\revLibs\main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\Administrator\Desktop\QQbot+VITS\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 89, in process_message
    raise e
  File "C:\Users\Administrator\Desktop\QQbot+VITS\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 47, in process_message
    for section in session.get_reply(prompt):
  File "C:\Users\Administrator\Desktop\QQbot+VITS\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 49, in get_reply
    for msg_, reply_period_dict in self.__rev_interface_impl__.get_reply(dprompt_, **kwargs):
  File "C:\Users\Administrator\Desktop\QQbot+VITS\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 72, in get_reply
    raise e
  File "C:\Users\Administrator\Desktop\QQbot+VITS\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 52, in get_reply
    for r in reply_gen:
  File "C:\Users\Administrator\Desktop\QQbot+VITS\QQbot\bot\python\lib\site-packages\revChatGPT\V1.py", line 172, in ask
    self.__check_response(response)
  File "C:\Users\Administrator\Desktop\QQbot+VITS\QQbot\bot\python\lib\site-packages\revChatGPT\V1.py", line 226, in __check_response
    raise error
revChatGPT.V1.Error

报错结束

设置revcfg.py
使用access_token，两种转发策略均做过尝试，该报错错误触发不明，时好时坏，私聊暂时尚未触发过，往往触发于群聊

**Comment by RockChinQ** [comment]
ChatGPT服务器问题，这两天都不稳定，这边也在尝试使用缓存鉴权信息解决问题，请关注 #24
