### ISSUE TITLE
更新插件后报错AttributeError: module 'config' has no attribute 'hide_exce_info_to_user'直接调用api用GPT3而不使用chatgpt

### ISSUE THREAD

**Issue by McPeter111** [RockChinQ/revLibs#30]
报错AttributeError: module 'config' has no attribute 'hide_exce_info_to_user'，更新插件后直接调用api而不使用chatgpt
![DC252F05-F562-4FAF-AC94-DE99508BAF85](https://user-images.githubusercontent.com/121279581/221401653-db8d1ba3-a894-41cc-9abc-2bac07801b12.jpeg)

**Comment by McPeter111** [comment]
代理日志显示已经连接了openai，结果客户端报错

**Comment by RockChinQ** [comment]
这可能是由于逆向库缓存引起的bug，请提供完整报错信息

**Comment by McPeter111** [comment]
(cmd)处理命令时出现错误，请联系管理员
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MIRAI-bot\QChatGPT\.\plugins\revLibs\main.py", line 117, in command_send
    reply_message = proccmd.process_command(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\Administrator\Desktop\MIRAI-bot\QChatGPT\.\plugins\revLibs\pkg\process\proccmd.py", line 12, in process_command
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 100, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 34, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "C:\Users\Administrator\Desktop\MIRAI-bot\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 27, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "C:\Users\Administrator\Desktop\MIRAI-bot\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 31, in __init__
    self.chatbot = Chatbot(
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 147, in __init__
    self.__check_credentials()
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 161, in __check_credentials
    self.__login()
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 271, in __login
    self.__refresh_headers(auth.access_token)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 183, in __refresh_headers
    self.__cache_access_token(email, access_token)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 230, in __cache_access_token
    self.__write_cache(cache)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MIRAI-bot\python\lib\site-packages\revChatGPT\V1.py", line 234, in __write_cache
    os.makedirs(osp.dirname(self.cache_path), exist_ok=True)
  File "os.py", line 225, in makedirs
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: ''


如果把登录模式从原来的账密换成accesstoken就不会有这个问题

**Comment by RockChinQ** [comment]
这是由于 acheong08/ChatGPT 的缓存机制bug导致的，暂时请尝试使用access_token登录

**Comment by RockChinQ** [comment]
上游依赖已修复 https://github.com/acheong08/ChatGPT/issues/947  
请执行`pip3 install revChatGPT --upgrade`
