### ISSUE TITLE
机器人在QQ群里不正常，加好友单独聊天正常

### ISSUE THREAD

**Issue by nanyansky** [RockChinQ/revLibs#34]
好友单独聊天可以正常调用网页版ChatGPT聊天，但在QQ群里@时就无法响应，有以下报错：

```
[2023-02-28 10:05:30.818] main.py (95) - [ERROR] : [rev] Traceback (most recent call last):
  File "/bot/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 102, in process_message
    raise e
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 49, in process_message
    for section in session.get_reply(prompt):
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 69, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/bot/plugins/revLibs/pkg/process/impls/v1impl.py", line 72, in get_reply
    raise e
  File "/bot/plugins/revLibs/pkg/process/impls/v1impl.py", line 52, in get_reply
    for r in reply_gen:
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 474, in ask
    if line.get("detail", {}).get("code") == "invalid_api_key":
AttributeError: 'str' object has no attribute 'get'
```

**Comment by RockChinQ** [comment]
Python版本是多少啊

**Comment by nanyansky** [comment]
> Python版本是多少啊

3.10.10

**Comment by RockChinQ** [comment]
我这里3.10测试没有复现问题，你可以尝试执行`pip3 install revChatGPT --upgrade`更新依赖库（不适用安装器版本及docker版本），或尝试更换OpenAI账号

**Comment by nanyansky** [comment]
> 我这里3.10测试没有复现问题，你可以尝试执行`pip3 install revChatGPT --upgrade`更新依赖库（不适用安装器版本及docker版本），或尝试更换OpenAI账号

好的好的，谢谢回复
