### ISSUE TITLE
支持在QQ对话中更新access_token

### ISSUE THREAD

**Issue by d4renk** [RockChinQ/revLibs#38]
access_token过期了，邮箱登录有时被Cloudflare拦截。希望access_token过期时通知管理员，并能够通过QQ对话提交session以更新access_token
```
[2023-03-01` 23:30:48.506] main.py (95) - [ERROR] : [rev] Traceback (most recent call last):
  File "/home/app/app/QChatGPT/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 100, in get_session
    __sessions__[name] = RevSession(name)
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 34, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 27, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 31, in __init__
    self.chatbot = Chatbot(
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 204, in __init__
    self.__check_credentials()
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 226, in __check_credentials
    raise Exception("Insufficient login details provided!")
Exception: Insufficient login details provided!

[2023-03-01 23:30:48.512] host.py (312) - [ERROR] : 插件revLibs触发事件person_normal_message_received时发生错误
[2023-03-01 23:30:48.513] host.py (313) - [ERROR] : Traceback (most recent call last):
  File "/home/app/app/QChatGPT/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 100, in get_session
    __sessions__[name] = RevSession(name)
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 34, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 27, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 31, in __init__
    self.chatbot = Chatbot(
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 204, in __init__
    self.__check_credentials()
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 226, in __check_credentials
    raise Exception("Insufficient login details provided!")
Exception: Insufficient login details provided!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/app/QChatGPT/pkg/plugin/host.py", line 306, in emit
    hook(plugin['instance'], **kwargs)
  File "/home/app/app/QChatGPT/plugins/revLibs/main.py", line 97, in normal_message_received
    if config.hide_exce_info_to_user:
AttributeError: module 'config' has no attribute 'hide_exce_info_to_user'

```

**Comment by RockChinQ** [comment]
安全性较低且access_token内容过多，不适合这样提交，且目前不建议使用ChatGPT逆向库
