### ISSUE TITLE
!reload后重启动mirai和bot ，发送任何字符都报以下错误

### ISSUE THREAD

**Issue by r5rinimaa** [RockChinQ/revLibs#4]
```
处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\压缩包\电脑的\QChatGPT\.\plugins\revLibs\main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\Administrator\Downloads\压缩包\电脑的\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 11, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\Administrator\Downloads\压缩包\电脑的\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 69, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\Administrator\Downloads\压缩包\电脑的\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 26, in __init__
    self.__rev_interface_impl__: RevLibInterface = __rev_interface_impl_class__()
  File "C:\Users\Administrator\Downloads\压缩包\电脑的\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 17, in __init__
    self.chatbot = Chatbot(
  File "C:\Users\Administrator\Downloads\压缩包\电脑的\python\lib\site-packages\revChatGPT\V1.py", line 65, in __init__
    self.__login()
  File "C:\Users\Administrator\Downloads\压缩包\电脑的\python\lib\site-packages\revChatGPT\V1.py", line 93, in __login
    auth.get_access_token()
  File "C:\Users\Administrator\Downloads\压缩包\电脑的\python\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 352, in get_access_token
    self.access_token = response.json()["accessToken"]
KeyError: 'accessToken'
```

**Comment by RockChinQ** [comment]
尝试以下步骤：请先[更新主程序](https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#-%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0%E4%BB%A3%E7%A0%81%E5%88%B0%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC) 之后使用管理员账号私聊机器人发送指令：`!plugin update`，然后重启主程序。    
此问题的上游依赖库issue：acheong08/ChatGPT#795

**Comment by nilfunc** [comment]
按照上面的步骤尝试未成功，得到以下报错
[2023-02-18 02:35:28.541] main.py (225) - [INFO] : 当前已是最新版本
[2023-02-18 02:35:29.864] main.py (121) - [ERROR] : [rev] Traceback (most recent call last):
  File "C:\Users\Kat\Desktop\QQbot\bot\QChatGPT\.\plugins\revLibs\main.py", line 112, in command_send
    reply_message = proccmd.process_command(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\Kat\Desktop\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\proccmd.py", line 9, in process_command
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\Kat\Desktop\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 70, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\Kat\Desktop\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 26, in __init__
    self.__rev_interface_impl__: RevLibInterface = __rev_interface_impl_class__()
  File "C:\Users\Kat\Desktop\QQbot\bot\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 17, in __init__
    self.chatbot = Chatbot(
  File "C:\Users\Kat\Desktop\QQbot\bot\python\lib\site-packages\revChatGPT\V1.py", line 65, in __init__
    self.__login()
  File "C:\Users\Kat\Desktop\QQbot\bot\python\lib\site-packages\revChatGPT\V1.py", line 101, in __login
    auth.get_access_token()
  File "C:\Users\Kat\Desktop\QQbot\bot\python\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 352, in get_access_token
    self.access_token = response.json()["accessToken"]
KeyError: 'accessToken'

[2023-02-18 02:35:29.865] process.py (119) - [INFO] : 回复[person_15]文字消息:[REV](cmd)处理命令时出现错误，请联系管理员
Traceback (most recent call last):
  File "C:\Users\Kat\Desktop\QQbot\bot...

**Comment by RockChinQ** [comment]
请更换使用accessToken的方式进行登录，请到revcfg.py中修改openai_account字段的值  
```
# 目前支持三种登录方式：账号密码登录、SessionToken登录、accessToken登录
# 1.适用于默认的注册方式得到的账号，2.适用于使用Google/Microsoft账号登录的账号，3.适用于中国大陆主机
# 以下默认使用账户密码方式登录。
#
# *若要使用SessionToken登录方式，请删掉email和password参数，添加session_token参数：
# 例如：
# openai_account = {
#   "session_token": "your session token"
# }
#
# *若要使用accessToken登录方式，请删掉email和password参数，添加access_token参数：
# 你可以在 https://chat.openai.com/api/auth/session 返回的数据中找到你的accessToken，记得先登录再获取
# 例如：
# openai_account = {
#   "access_token": "your access token"
# }
```
