### ISSUE TITLE
长问答一直重试 超过设定次数后会报无效参数：mirai.exceptions.ApiError: (400, '[ERROR 400]参数错误。', '无效参数')

### ISSUE THREAD

**Issue by 1QinSe** [RockChinQ/revLibs#5]
![image](https://user-images.githubusercontent.com/94440319/219658296-2c2529e9-86af-4715-8bd1-08fbfeb727b4.png)

[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "/bot/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 76, in process_message
    raise e
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 63, in process_message
    host.send_person_message(kwargs['launcher_id'], message_chain)
  File "/bot/pkg/plugin/host.py", line 261, in send_person_message
    asyncio.run(self.get_bot().send_friend_message(person, message))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 430, in __call__
    return await self.set(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 398, in set
    return await self._call_api(
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 386, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 318, in call
    raw_response = await self._call(api_provider, method)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 304, in _call
    return await api_provider.call_api(
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 320, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (400, '[ERROR 400]参数错误。', '无效参数')

**Comment by RockChinQ** [comment]
你这个使用的长消息发送策略是什么啊，revcfg.py中的blog_msg_strategy字段

**Comment by 1QinSe** [comment]
默认的256  
![image](https://user-images.githubusercontent.com/94440319/219837139-7e4b929e-70c1-40e0-aea5-bb7ad4903e1f.png)

**Comment by RockChinQ** [comment]
尝试改为使用accessToken登录

**Comment by Speechless22** [comment]
经我测试，同样的问题用"send_section"策略时分段回答很顺利，用"forward_msg_component"策略时会报如下错误

[2023-02-19 19:03:51.455] procmsg.py (65) - [INFO] : [rev] 回复person_消息：升级OpenWrt固件的步骤可以分为以下
几个步骤：

1. 打开终端或命令行工具：您可以使用SSH协
Traceback (most recent call last):
  File "/home/ubuntu/Femirins/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 70, in process_message
    host.send_person_message(kwargs['launcher_id'], message_chain)
  File "/home/ubuntu/Femirins/QChatGPT/pkg/plugin/host.py", line 261, in send_person_message
    asyncio.run(self.get_bot().send_friend_message(person, message))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/models/api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/models/api.py", line 383, in set
    return await self._call_api(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/models/api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/models/api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (400, '[ERROR 400]参数错误。', '无效参数')

**Comment by RockChinQ** [comment]
> 经我测试，同样的问题用"send_section"策略时分段回答很顺利，用"forward_msg_component"策略时会报如下错误
> 
> ```
> [2023-02-19 19:03:51.455] procmsg.py (65) - [INFO] : [rev] 回复person_消息：升级OpenWrt固件的步骤可以分为以下
> 几个步骤：
> 
> 1. 打开终端或命令行工具：您可以使用SSH协
> Traceback (most recent call last):
>   File "/home/ubuntu/Femirins/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 70, in process_message
>     host.send_person_message(kwargs['launcher_id'], message_chain)
>   File "/home/ubuntu/Femirins/QChatGPT/pkg/plugin/host.py", line 261, in send_person_message
>     asyncio.run(self.get_bot().send_friend_message(person, message))
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/models/api.py", line 415, in __call__
>     return await self.set(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/models/api.py", line 383, in set
>     return await self._call_api(
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/models/api.py", line 373, in _call_api
>     return await api.call(self.api_provider, method, response_type)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/models/api.py", line 304, in call
>     raw_response = await api_provider.call_api(
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/bot.py", line 91, in call_api
>     return await self._adapter.call_api(api, *args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 236, in call_api
>     return await self._recv(sync_id)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 165, in _recv
>     raise exceptions.ApiError(data)
> mirai.exceptions.ApiError: (400, '[ERROR 400]参数错误。', '无效参数')
> ```

那有可能是上游依赖(YiriMirai)的问题

**Comment by RockChinQ** [comment]
估计是YiriMirai库对消息转发组件操作的bug，遇到此问题的朋友：建议先将`revcfg.py`中的`blog_msg_strategy`修改为分节发送的策略，或将`blog_msg_threshold`设置为一个极大的值以避免使用消息转发组件。

**Comment by Speechless22** [comment]
[YiriMirai](https://github.com/YiriMiraiProject/YiriMirai)目前无人维护，最后一个完全支持的 mirai-api-http 版本为 2.5

**Comment by RockChinQ** [comment]
> [YiriMirai](https://github.com/YiriMiraiProject/YiriMirai)目前无人维护，最后一个完全支持的 mirai-api-http 版本为 2.5

这是事实，但一方面我可以尝试重写其中有bug的地方，再者已经有人提出有意向维护此项目

**Comment by RockChinQ** [comment]
WIP

**Comment by RockChinQ** [comment]
已重写YiriMirai中的过时代码，请更新
