### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

### ISSUE THREAD

**Issue by d4renk** [RockChinQ/revLibs#52]
**部署环境是debian11 python3.9**

```
[2023-03-09 23:17:30.591] keymgr.py (62) - [INFO] : 使用api-key:default
[2023-03-09 23:17:30.593] manager.py (30) - [INFO] : 文字总使用量：89096
[2023-03-09 23:17:30.594] session.py (67) - [INFO] : 加载session: person_***
[2023-03-09 23:17:30.597] manager.py (95) - [INFO] : 加载禁用列表: person: [***], group: [***]
[2023-03-09 23:17:30.597] host.py (88) - [INFO] : 加载插件
[2023-03-09 23:17:30.601] models.py (219) - [INFO] : 插件注册完成: n='加群审批', d='自动审批加群申请', v=0.1, a='RockChinQ' (<class 'plugins.auto_approval.main.AutoApproval'>)
[2023-03-09 23:17:30.602] host.py (80) - [INFO] : 加载模块: plugins/auto_approval/main.py 成功
[2023-03-09 23:17:30.603] models.py (219) - [INFO] : 插件注册完成: n='CmdCN', d='命令中文支持', v=0.1, a='RockChinQ' (<class 'plugins.cmdcn.cmdcn.CmdCnPlugin'>)
[2023-03-09 23:17:30.604] host.py (80) - [INFO] : 加载模块: plugins/cmdcn/cmdcn.py 成功
[2023-03-09 23:17:30.605] models.py (219) - [INFO] : 插件注册完成: n='Hello', d='hello world', v=0.1, a='RockChinQ' (<class 'plugins.hello_plugin.main.HelloPlugin'>)
[2023-03-09 23:17:30.606] host.py (80) - [INFO] : 加载模块: plugins/hello_plugin/main.py 成功
[2023-03-09 23:17:30.691] models.py (219) - [INFO] : 插件注册完成: n='revLibs', d='接入acheong08/ChatGPT等逆向库', v=0.2.0, a='RockChinQ' (<class 'plugins.revLibs.main.RevLibsPlugin'>)
[2023-03-09 23:17:30.693] host.py (80) - [INFO] : 加载模块: plugins/revLibs/main.py 成功
[2023-03-09 23:17:30.694] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/process/proccmd.py 成功
[2023-03-09 23:17:30.695] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/process/procmsg.py 成功
[2023-03-09 23:17:30.696] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/process/revss.py 成功
[2023-03-09 23:17:30.699] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/utils.py 成功
[2023-03-09 23:17:30.700] host.py (80) - [INFO] : 加载模块: plugins/revLibs/revcfg-template.py 成功
[2023-03-09 23:17:30.702] models.py (219) - [INFO] : 插件注册完成: n='啊对对对', d='你都这样了，我就顺从你吧', v=0.1, a='RockChinQ' (<class 'plugins.urlikethisijustsix.urlt.AdddPlugin'>)
[2023-03-09 23:17:30.703] host.py (80) - [INFO] : 加载模块: plugins/urlikethisijustsix/urlt.py 成功
[2023-03-09 23:17:30.704] host.py (105) - [INFO] : 初始化插件
[2023-03-09 23:17:30.704] host.py (113) - [INFO] : 插件 加群审批 已初始化
[2023-03-09 23:17:30.706] host.py (113) - [INFO] : 插件 CmdCN 已初始化
[2023-03-09 23:17:30.706] host.py (113) - [INFO] : 插件 Hello 已初始化
[2023-03-09 23:17:30.708] host.py (113) - [INFO] : 插件 啊对对对 已初始化
[2023-03-09 23:17:30.708] main.py (69) - [INFO] : [rev] 逆向库初始化成功
[2023-03-09 23:17:30.709] main.py (81) - [INFO] : [rev] 已将主程序消息处理超时时间设置为10分钟
[2023-03-09 23:17:30.710] host.py (113) - [INFO] : 插件 revLibs 已初始化
[2023-03-09 23:17:30.712] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-03-09 23:17:30.825] websocket.py (194) - [INFO] : [WebSocket] 成功登录到账号***。
[2023-03-09 23:17:30.827] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-03-09 23:17:38.357] procmsg.py (25) - [INFO] : [rev] 收到person_***消息: proxy
[2023-03-09 23:17:38.438] procmsg.py (110) - [WARNING] : 失败，重试(1/2)...
[2023-03-09 23:17:40.544] procmsg.py (110) - [WARNING] : 失败，重试(2/2)...
[2023-03-09 23:17:42.609] main.py (95) - [ERROR] : [rev] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/app/QChatGPT/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 114, in process_message
    raise e
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 58, in process_message
    for section in session.get_reply(prompt):
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 69, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 72, in get_reply
    raise e
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 52, in get_reply
    for r in reply_gen:
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 503, in ask
    response = self.session.post(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='chat.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

[2023-03-09 23:17:42.613] host.py (314) - [ERROR] : 插件revLibs触发事件person_normal_message_received时发生错误
[2023-03-09 23:17:42.615] host.py (315) - [ERROR] : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/app/QChatGPT/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 114, in process_message
    raise e
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 58, in process_message
    for section in session.get_reply(prompt):
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 69, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 72, in get_reply
    raise e
  File "/home/app/app/QChatGPT/plugins/revLibs/pkg/process/impls/v1impl.py", line 52, in get_reply
    for r in reply_gen:
  File "/home/app/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 503, in ask
    response = self.session.post(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='chat.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/app/QChatGPT/pkg/plugin/host.py", line 308, in emit
    hook(plugin['instance'], **kwargs)
  File "/home/app/app/QChatGPT/plugins/revLibs/main.py", line 99, in normal_message_received
    host.notify_admin("[rev] 处理消息时出现错误:\n"+traceback.format_exc())
AttributeError: module 'pkg.plugin.host' has no attribute 'notify_admin'

[2023-03-09 23:17:42.621] message.py (29) - [INFO] : [person_***]发送消息:proxy
[2023-03-09 23:17:42.724] main.py (261) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-03-09 23:17:48.032] main.py (292) - [INFO] : 当前已是最新版本
[2023-03-09 23:17:49.653] util.py (67) - [INFO] : message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=6404 request_id=*** response_code=200
[2023-03-09 23:17:49.712] process.py (155) - [INFO] : 回复[person_***]文字消息:[GPT]代理（Proxy）是一种计算机网络技术，它充当客户端和服务器之间的中介。代理服务器接收来自客户端的请求，并将其转发给目标服务器，然后将响应返回给客户端。代理可以用于多种目的，例如提高安全性、...

```

**revcfg.py**

```
# 选择使用的逆向库
# 目前支持以下库：
# - "acheong08/ChatGPT.V1": acheong08/ChatGPT库的V1版本
reverse_lib = "acheong08/ChatGPT.V1"

# [必填][❗此说明很重要，请您认真阅读❗] OpenAI账户信息
# 目前支持三种登录方式：账号密码登录、SessionToken登录、accessToken登录
# 1.适用于默认的注册方式得到的账号，2.适用于使用Google/Microsoft账号登录的账号，3.适用于中国大陆主机
# 以下默认使用账户密码方式登录。
#
# *若要使用SessionToken登录方式，请删掉email和password参数，添加session_token参数：
# 例如：
# openai_account = {
#   "session_token": "your session token"
# }
#
# *若要使用accessToken登录方式，请删掉email和password参数，添加access_token参数：
# 你可以在 https://chat.openai.com/api/auth/session 返回的数据中找到你的accessToken，记得先登录再获取
# 例如：
# openai_account = {
#   "access_token": "your access token"
# }
#
# 除了登录信息，还支持以下可选参数：
#  - proxy: 代理服务器地址，格式为"protocol:ip:port"，例如"https://localhost:1080"
#  - paid: 是否订阅了ChatGPT Plus服务，若为True则使用ChatGPT Plus服务
#
# **若要使用多个账户均衡负载，可以以列表的形式添加多个账户信息，例如：
# openai_account = [
#   {
#     "email": "your email",
#     "password": "your password"
#   },
#   {
#     "email": "your email",
#     "password": "your password"
#   }
# ]
# 其中每个账户的格式符合前文所述的格式
#openai_account = [
#    {
#        "email": "your email",  # 账户邮箱
#        "password": "your password",  # 账户密码
#    }
#]
# "proxy": "http://127.0.0.1:7890"

openai_account = {
    "access_token": "***"
}

# 账号重新恢复使用的时间间隔
# 以分钟为单位
openai_account_resume_interval = 60

# 消息回复前缀
# 建议保留此前缀，以便区分GPT-3和此插件的回复
reply_prefix = "[REV]"

# 获取回复失败时的重试次数
# 若为0则不重试
retry_when_fail = 2

# 超长消息阈值
# 若消息长度超过此阈值，则按照以下策略处理
# 如果你不需要使用分节功能（即任何消息都以普通消息的形式回复），
# 请将此值设置为超大的值（如 2147483647）
blog_msg_threshold = 2147483647

# 超长消息处理策略
# - "send_section": 发送前部分消息，继续等待回复
# - "forward_msg_component": 以转发消息的形式发送
blog_msg_strategy = "send_section"
```

**Comment by RockChinQ** [comment]
ChatGPT的逆向访问方式现已不再可用，请考虑使用项目主线的ChatGPT API
