### ISSUE TITLE
下载最新版提示TypeError: can only concatenate list (not "str") to list

### ISSUE THREAD

**Issue by qssq1** [RockChinQ/revLibs#57]
```
raceback (most recent call last):
  File "E:\dev\整合包window快速部署\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 58, in process_message
    for section in session.get_reply(prompt):
  File "E:\dev\整合包window快速部署\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 65, in get_reply
    prompt = dprompt_ +" \n"+ prompt
TypeError: can only concatenate list (not "str") to list
[2023-03-12 21:50:59.260] procmsg.py (110) - [WARNING] : 失败，重试(1/1)...
Traceback (most recent call last):
  File "E:\dev\整合包window快速部署\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 58, in process_message
    for section in session.get_reply(prompt):
  File "E:\dev\整合包window快速部署\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 65, in get_reply
    prompt = dprompt_ +" \n"+ prompt
TypeError: can only concatenate list (not "str") to list
[2023-03-12 21:51:01.265] main.py (95) - [ERROR] : [rev] Traceback (most recent call last):
  File "E:\dev\整合包window快速部署\bot3\QChatGPT\.\plugins\revLibs\main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "E:\dev\整合包window快速部署\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 114, in process_message
    raise e
  File "E:\dev\整合包window快速部署\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 58, in process_message
    for section in session.get_reply(prompt):
  File "E:\dev\整合包window快速部署\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 65, in get_reply
    prompt = dprompt_ +" \n"+ prompt
TypeError: can only concatenate list (not "str") to list
```

**Comment by RockChinQ** [comment]
这是一个兼容性问题 #54

**Comment by RockChinQ** [comment]
已修复，请使用 `!plugin update`指令更新
