### ISSUE TITLE
revLib报错，无法使用

### ISSUE THREAD

**Issue by wenyinos** [RockChinQ/revLibs#60]
### QChatGPT使用一键安装包部署，安装revLib重载后出现下列错误：
`[rev] Traceback (most recent call last):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 114, in process_message
    raise e
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 58, in process_message
    for section in session.get_reply(prompt):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 65, in get_reply
    prompt = dprompt_ +" \n"+ prompt
TypeError: can only concatenate list (not "str") to list

[2023-03-13 19:27:20.280] host.py (314) - [ERROR] : 插件revLibs触发事件person_normal_message_received时发生错误
[2023-03-13 19:27:20.281] host.py (315) - [ERROR] : Traceback (most recent call last):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 114, in process_message
    raise e
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 58, in process_message
    for section in session.get_reply(prompt):
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 65, in get_reply
    prompt = dprompt_ +" \n"+ prompt
TypeError: can only concatenate list (not "str") to list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wenyinos/qcg-bot/QChatGPT/pkg/plugin/host.py", line 308, in emit
    hook(plugin['instance'], **kwargs)
  File "/home/wenyinos/qcg-bot/QChatGPT/plugins/revLibs/main.py", line 99, in normal_message_received
    host.notify_admin("[rev] 处理消息时出现错误:\n"+traceback.format_exc())
AttributeError: module 'pkg.plugin.host' has no attribute 'notify_admin'`

**Comment by RockChinQ** [comment]
#57

**Comment by RockChinQ** [comment]
已修复，请使用 `!plugin update`指令更新
