### ISSUE TITLE
逆向库不再进行长消息处理

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/revLibs#65]
将全文发送给主程序处理

**Comment by CBEpt** [comment]
```
[2023-03-28 10:29:12.105] procmsg.py (19) - [INFO] : [rev] 收到person_xxxxxxxxxx消息: 1
Traceback (most recent call last):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
    dprompt_ = dprompt.get_prompt(dprompt.get_current())
AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
[2023-03-28 10:29:12.109] procmsg.py (54) - [WARNING] : 失败，重试(1/3)...
Traceback (most recent call last):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
    dprompt_ = dprompt.get_prompt(dprompt.get_current())
AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
[2023-03-28 10:29:14.113] procmsg.py (54) - [WARNING] : 失败，重试(2/3)...
Traceback (most recent call last):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
    dprompt_ = dprompt.get_prompt(dprompt.get_current())
AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
[2023-03-28 10:29:16.118] procmsg.py (54) - [WARNING] : 失败，重试(3/3)...
Traceback (most recent call last):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
    dprompt_ = dprompt.get_prompt(dprompt.get_current())
AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
[2023-03-28 10:29:18.134] main.py (112) - [ERROR] : [rev] Traceback (most recent call last):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 58, in process_message
    raise e
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
    dprompt_ = dprompt.get_prompt(dprompt.get_current())
AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'

[2023-03-28 10:29:18.135] process.py (156) - [INFO] : 回复[person_xxxxxxxxxx]文字消息:[rev]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
```

请问这应该怎么办。。

**Comment by RockChinQ** [comment]
> ```
> [2023-03-28 10:29:12.105] procmsg.py (19) - [INFO] : [rev] 收到person_xxxxxxxxxx消息: 1
> Traceback (most recent call last):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
>     for section in session.get_reply(prompt):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
>     dprompt_ = dprompt.get_prompt(dprompt.get_current())
> AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
> [2023-03-28 10:29:12.109] procmsg.py (54) - [WARNING] : 失败，重试(1/3)...
> Traceback (most recent call last):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
>     for section in session.get_reply(prompt):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
>     dprompt_ = dprompt.get_prompt(dprompt.get_current())
> AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
> [2023-03-28 10:29:14.113] procmsg.py (54) - [WARNING] : 失败，重试(2/3)...
> Traceback (most recent call last):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
>     for section in session.get_reply(prompt):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
>     dprompt_ = dprompt.get_prompt(dprompt.get_current())
> AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
> [2023-03-28 10:29:16.118] procmsg.py (54) - [WARNING] : 失败，重试(3/3)...
> Traceback (most recent call last):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
>     for section in session.get_reply(prompt):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
>     dprompt_ = dprompt.get_prompt(dprompt.get_current())
> AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
> [2023-03-28 10:29:18.134] main.py (112) - [ERROR] : [rev] Traceback (most recent call last):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\main.py", line 105, in normal_message_received
>     reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 58, in process_message
>     raise e
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
>     for section in session.get_reply(prompt):
>   File "C:\Users\Administator\Desktop\qchat\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 79, in get_reply
>     dprompt_ = dprompt.get_prompt(dprompt.get_current())
> AttributeError: module 'pkg.openai.dprompt' has no attribute 'get_prompt'
> 
> [2023-03-28 10:29:18.135] process.py (156) - [INFO] : 回复[person_xxxxxxxxxx]文字消息:[rev]处理消息时出现错误，请联系管理员
> Traceback (most recent call last):
> ```
> 
> 请问这应该怎么办。。

#103
