### ISSUE TITLE
接入New Bing后无法使用

### ISSUE THREAD

**Issue by DannyLI0319** [RockChinQ/revLibs#66]
我是在这个页面抓的cookie:
![YD63%MXRFCZYGB{17DSRN9I](https://user-images.githubusercontent.com/120266145/225339756-2d7274b5-66a8-480c-a644-41f5a7df08d1.png)

这是报错：
[2023-03-15 22:24:31.674] main.py (95) - [ERROR] : [rev] Traceback (most recent call last):
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\.\plugins\revLibs\main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 100, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 34, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 27, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 31, in __init__
    self.chatbot = Chatbot(
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 233, in __init__
    self.__check_credentials()
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 258, in __check_credentials
    raise error
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 256, in __check_credentials
    self.__login()
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 401, in __login
    auth.begin()
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "C:\Users\kuang\Desktop\ChatGPT\python\lib\site-packages\OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error

**Comment by RockChinQ** [comment]
你这没改逆向库，根据文档

> 修改`revcfg.py`中的`reverse_lib`为`acheong08/EdgeGPT`

**Comment by water-root** [comment]
改了还报错，咋回事啊

**Comment by RockChinQ** [comment]
> 改了还报错，咋回事啊

提供配置文件截图

**Comment by water-root** [comment]
![QQ图片20230316101141](https://user-images.githubusercontent.com/124557984/225491989-08f73d13-b8bd-483e-a3c9-a6ac2ff0ab35.png)

**Comment by RockChinQ** [comment]
没有问题，请贴出报错信息



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 上午10:13
收件人: ***@***.***&gt;;
抄送: "Rock ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [RockChinQ/revLibs] 接入New Bing后无法使用 (Issue #66)

**Comment by water-root** [comment]
[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "/bot/plugins/revLibs/main.py", line 97, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 108, in get_session
    __sessions__[name] = RevSession(name)
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 35, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "/bot/plugins/revLibs/pkg/process/impls/v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "/bot/plugins/revLibs/pkg/process/impls/v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 237, in __init__
    self.__check_credentials()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 270, in __check_credentials
    raise error
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 268, in __check_credentials
    self.login()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 413, in login
    auth.begin()
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 210, in __part_four
    raise Error(
OpenAIAuth.Error

**Comment by RockChinQ** [comment]
确认你修改的是不是主程序的`config.py`同目录下的`revcfg.py`

**Comment by DannyLI0319** [comment]
这个问题我昨天解决了，提供方法
1.删除plug in 下面的rev文件夹，完整删除，不要重命名
2.重新通过指令install插件
3.重启bot，收到更新提升，!update 
4.指令更新插件!plugin update 
5.重启bot
6.手动用cmd cd到python 文件夹安装edge gpt，具体指令看edge GPT 原帖
7.重启bot，指令更新插件
8.按说明编辑rev config ，包括修改lab，配置cookie 
9.重启bot
10.重新尝试，问题解决

注意：
以上只是我解决的我的问题的步骤，不代表每一步都是必须的
以上所有指令都是手机手打，表达个一起，具体正确指令看其他issue，都是些基础的

**Comment by DannyLI0319** [comment]
顺便补充下问题排查步骤
先是怀疑cookie ，后面换了大佬的cookie ，还是有问题，排除cookie 的可能性
然后仔细看代码，发现是lib指向，但是确认过配置文件没问题
最后就是各种方法更新配置文件和插件，都不行，直接删除插件重新装，解决了

请特别注意，如果你把原来的rev文件夹，copy 一个新的，删除原来的，然后重装，系统会生成一个新的rev，但是看代码，发现还是指向rev - copy，所以一定要彻底删除，不要尝试改名或者在同文件夹下复制一个备份
