### ISSUE TITLE
请问用谷歌账号登陆plus的怎么设置呀

### ISSUE THREAD

**Issue by zutomayo11** [RockChinQ/revLibs#67]
![5RV MZ}GGK 98UD3%B6AAQY](https://user-images.githubusercontent.com/127024045/225348736-b0d72887-2c8d-4a6b-a82d-3a97a64b64fc.png)

**Comment by zutomayo11** [comment]
报错如下
[2023-03-15 22:49:08.405] main.py (104) - [ERROR] : [rev] Traceback (most recent call last):
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\main.py", line 97, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 108, in get_session
    __sessions__[name] = RevSession(name)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 35, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 237, in __init__
    self.__check_credentials()
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 270, in __check_credentials
    raise error
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 268, in __check_credentials
    self.login()
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 413, in login
    auth.begin()
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 247, in __part_five
    raise Error(
OpenAIAuth.Error

[2023-03-15 22:49:08.406] host.py (314) - [ERROR] : 插件revLibs触发事件person_normal_message_received时发生错误
[2023-03-15 22:49:08.407] host.py (315) - [ERROR] : Traceback (most recent call last):
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\main.py", line 97, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 108, in get_session
    __sessions__[name] = RevSession(name)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 35, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 237, in __init__
    self.__check_credentials()
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 270, in __check_credentials
    raise error
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 268, in __check_credentials
    self.login()
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 413, in login
    auth.begin()
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 247, in __part_five
    raise Error(
OpenAIAuth.Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\robot\robot\bot3\QChatGPT\.\pkg\plugin\host.py", line 308, in emit
    hook(plugin['instance'], **kwargs)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\main.py", line 108, in normal_message_received
    host.notify_admin("[rev] 处理消息时出现错误:\n"+traceback.format_exc())
AttributeError: module 'pkg.plugin.host' has no attribute 'notify_admin'

**Comment by RockChinQ** [comment]
配置文件填的是什么

**Comment by zutomayo11** [comment]
> 配置文件填的是什么

忘传了，刚发

**Comment by RockChinQ** [comment]
账户登录设置都写到`openai_account`里，例如

```python
openai_account = [
    {
        "email": "xxx",
        "password": "xxx",
        "paid": True,
        "proxy": "xxx"
    }
]
```

**Comment by zutomayo11** [comment]
> 账户登录设置都写到`openai_account`里，例如
> 
> ```python
> openai_account = [
>     {
>         "email": "xxx",
>         "password": "xxx",
>         "paid": True,
>         "proxy": "xxx"
>     }
> ]
> ```

还是和刚才一样的报错

**Comment by RockChinQ** [comment]
> > 账户登录设置都写到`openai_account`里，例如
> > ```python
> > openai_account = [
> >     {
> >         "email": "xxx",
> >         "password": "xxx",
> >         "paid": True,
> >         "proxy": "xxx"
> >     }
> > ]
> > ```
> 
> 还是和刚才一样的报错

再贴一下新的报错，以及你新填写的配置文件

**Comment by zutomayo11** [comment]
> 

[2023-03-15 23:16:59.598] main.py (104) - [ERROR] : [rev] Traceback (most recent call last):
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\main.py", line 97, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 108, in get_session
    __sessions__[name] = RevSession(name)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 35, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 237, in __init__
    self.__check_credentials()
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 270, in __check_credentials
    raise error
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 268, in __check_credentials
    self.login()
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 413, in login
    auth.begin()
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 247, in __part_five
    raise Error(
OpenAIAuth.Error

[2023-03-15 23:16:59.598] host.py (314) - [ERROR] : 插件revLibs触发事件person_normal_message_received时发生错误
[2023-03-15 23:16:59.599] host.py (315) - [ERROR] : Traceback (most recent call last):
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\main.py", line 97, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 108, in get_session
    __sessions__[name] = RevSession(name)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 35, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 237, in __init__
    self.__check_credentials()
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 270, in __check_credentials
    raise error
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 268, in __check_credentials
    self.login()
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\robot\robot\bot3\python\lib\site-packages\revChatGPT\V1.py", line 413, in login
    auth.begin()
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "D:\robot\robot\bot3\python\lib\site-packages\OpenAIAuth.py", line 247, in __part_five
    raise Error(
OpenAIAuth.Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\robot\robot\bot3\QChatGPT\.\pkg\plugin\host.py", line 308, in emit
    hook(plugin['instance'], **kwargs)
  File "D:\robot\robot\bot3\QChatGPT\.\plugins\revLibs\main.py", line 108, in normal_message_received
    host.notify_admin("[rev] 处理消息时出现错误:\n"+traceback.format_exc())
AttributeError: module 'pkg.plugin.host' has no attribute 'notify_admin'
![ZIQMUGW{LT8~NM%TS1A`QON](https://user-images.githubusercontent.com/127024045/225356057-2a466155-c72a-4747-b069-bd362c555f44.png)

**Comment by zutomayo11** [comment]
> > > 账户登录设置都写到`openai_account`里，例如
> > > ```python
> > > openai_account = [
> > >     {
> > >         "email": "xxx",
> > >         "password": "xxx",
> > >         "paid": True,
> > >         "proxy": "xxx"
> > >     }
> > > ]
> > > ```
> > 
> > 
> > 还是和刚才一样的报错
> 
> 再贴一下新的报错，以及你新填写的配置文件

是因为谷歌登录的得用session token吗
