### ISSUE TITLE
第一次安装报错

### ISSUE THREAD

**Issue by xiaoqianshenlu** [RockChinQ/revLibs#76]
[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\QChatGPT\.\plugins\revLibs\main.py", line 101, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 108, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 35, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\revChatGPT\V1.py", line 237, in __init__
    self.__check_credentials()
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\revChatGPT\V1.py", line 270, in __check_credentials
    raise error
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\revChatGPT\V1.py", line 268, in __check_credentials
    self.login()
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\revChatGPT\V1.py", line 413, in login
    auth.begin()
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot1\bot5\python\lib\site-packages\OpenAIAuth.py", line 210, in __part_four
    raise Error(
OpenAIAuth.Error

**Comment by RockChinQ** [comment]
你要使用哪个逆向库？

**Comment by xiaoqianshenlu** [comment]
newbing的

**Comment by RockChinQ** [comment]
那你运行了一次之后生成了`revcfg.py`文件，就去`revcfg.py`中按照文档的`new bing` 的配置步骤进行更改，然后重启程序

**Comment by xiaoqianshenlu** [comment]
还是一样

[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\main.py", line 101, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 41, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 30, in create_instance
    cookies_dict = json.load(f)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Unterminated string starting at: line 72 column 17 (char 1973)

**Comment by RockChinQ** [comment]
cookies填写内容不完整，重新按照步骤填写

**Comment by xiaoqianshenlu** [comment]
我是复制的cookies的值。但重启了之后还是报错

**Comment by xiaoqianshenlu** [comment]
报错结果类似

[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\main.py", line 101, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 41, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "C:\Users\Administrator\Downloads\新建文件夹\bot3\bot4\bot2\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 30, in create_instance
    cookies_dict = json.load(f)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
