### ISSUE TITLE
使用New Bing报错

### ISSUE THREAD

**Issue by Hanserwei** [RockChinQ/revLibs#84]
请您认真填写以下信息。

### 任务

- [ ] 我已严格按照文档中的步骤操作
- [ ] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：New Bing

### 期望情况

我希望的情况是：填写完毕，重启主程序，然后成功！

### 实际情况

实际情况是：

[inf.txt](https://github.com/RockChinQ/revLibs/files/11037790/inf.txt)
[inf.txt](https://github.com/RockChinQ/revLibs/files/11037792/inf.txt)
[2023-03-22 08:11:13.786] procmsg.py (19) - [INFO] : [rev] 收到person_2628273921消息: 你好
[2023-03-22 08:11:16.702] main.py (108) - [ERROR] : [rev] Traceback (most recent call last):
  File "/bot/plugins/revLibs/main.py", line 101, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 36, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "/bot/plugins/revLibs/pkg/process/impls/v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "/bot/plugins/revLibs/pkg/process/impls/v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 163, in __init__
    self.__check_credentials()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 189, in __check_credentials
    raise error
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 187, in __check_credentials
    self.login()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 335, in login
    auth.begin()
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth.py", line 210, in __part_four
    raise Error(
OpenAIAuth.Error

**Comment by RockChinQ** [comment]
你这个没切换到newbing，关闭程序，修改revcfg.py里的设置再启动，注意是config.py同目录的revcfg.py
