### ISSUE TITLE
ModuleNotFoundError: No module named 'EdgeGPT'

### ISSUE THREAD

**Issue by Lingpeixie** [RockChinQ/revLibs#86]
正在使用的逆向库

我要使用的逆向库是：New Bing

实际情况是：
revcfg.py文件没有被自动创建
reload失败
提示以下内容
[2023-03-23 03:54:42.293] host.py (83) - [ERROR] : 加载模块: plugins/revLibs/pkg/process/revss.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'EdgeGPT'"), <traceback object at 0x0000021B129B6DC0>)
Traceback (most recent call last):
  File "F:\Qchat\bot3\QChatGPT\.\pkg\plugin\host.py", line 80, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Qchat\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 4, in <module>
    from plugins.revLibs.pkg.process.impls.edgegpt import EdgeGPTImpl
  File "F:\Qchat\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 9, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
ModuleNotFoundError: No module named 'EdgeGPT'

检查过了环境变量，已配置如下
C:\Users\admin\AppData\Local\Programs\Python\Python311\Scripts\
C:\Users\admin\AppData\Local\Programs\Python\Python311\
C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages

C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages中能看到EdgeGPT.py和以下几个文件夹
EdgeGPT-0.1.3-py3.11.egg-info、revChatGPT、revChatGPT-4.0.5.dist-info

**Comment by RockChinQ** [comment]
检查一下你运行此程序的python是不是你查看是否有edgegpt的python环境

**Comment by Lingpeixie** [comment]
已解决
在QchatGPT的main.py的import sys下方加入
print("Python 版本：", sys.version)
print("Python 可执行文件路径：", sys.executable)
print("Python 环境路径：", os.environ["PATH"])

发现路径不是我安装的python路径
是整合包中的python路径，但是我比较菜不会换程序使用的python版本

所以进入到当前使用的python路径执行python.exe -m pip install EdgeGPT --upgrade
在当前目录的python中安装EdgeGPT后，把这个目录的pyhton.exe的路径和lib文件夹的路径添加到环境变量

运行QchatGPT，成功加载逆向插件
