### ISSUE TITLE
Exception: Authentication failed

### ISSUE THREAD

**Issue by Lingpeixie** [RockChinQ/revLibs#87]
似乎是身份验证问题，插件加载成功了，revcfg.py中填的是第一种账密登录模式，cookie是按照流程打开bing.com存的，存之前确认过能打开newbing的对话窗口，用的内陆自己的台式，代理持续挂着

发送聊天消息：你好
返回以下内容

[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "F:\BOT\bot3\QChatGPT\.\plugins\revLibs\main.py", line 101, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "F:\BOT\bot3\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "F:\BOT\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "F:\BOT\bot3\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 41, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "F:\BOT\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 32, in create_instance
    return EdgeGPTImpl(cookies_dict, ConversationStyle.creative), True, cookies_dict
  File "F:\BOT\bot3\QChatGPT\.\plugins\revLibs\pkg\process\impls\edgegpt.py", line 36, in __init__
    self.chatbot = Chatbot(cookies=cookies)
  File "F:\BOT\bot3\python\lib\site-packages\EdgeGPT.py", line 308, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "F:\BOT\bot3\python\lib\site-packages\EdgeGPT.py", line 220, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed

**Comment by RockChinQ** [comment]
请使用issue模板重新创建
