### ISSUE TITLE
使用EdgeGPT时报错

### ISSUE THREAD

**Issue by wzh195879702** [RockChinQ/revLibs#88]
[2023-03-23 19:15:27.893] manager.py (337) - [INFO] : 通知管理员:[rev] 处理消息时出现错误:
Traceback (most recent call last):
  File "/root/QChatGPT/plugins/revLibs/main.py", line 101, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 38, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 41, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 32, in create_instance
    return EdgeGPTImpl(cookies_dict, ConversationStyle.creative), True, cookies_dict
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 36, in __init__
    self.chatbot = Chatbot(cookies=cookies)
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 307, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 220, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed
昨天还可以正常使用今天就不行了

**Comment by wzh195879702** [comment]
不行，还是这个错误

> 可能是逆向库版本过低，请使用`!plugin update`指令尝试进行更新

**Comment by RockChinQ** [comment]
#98，已修复，请使用指令!plugin update更新
