### ISSUE TITLE
AttributeError: harmonyv3

### ISSUE THREAD

**Issue by niliovo** [RockChinQ/revLibs#92]
请您认真填写以下信息。

### 任务

- [x] 我已严格按照文档中的步骤操作
- [x] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：EdgeGPT（例如：New Bing）

### 期望情况

我希望的情况是：

### 实际情况

实际情况是：

EdgeGPT~=0.1.4 这个版本正常使用
当我使用 !plugin update 更新到 EdgeGPT~=0.1.6 版本后出现的异常

[2023-03-24 04:47:01.336] revss.py (74) - [INFO] : [rev] 使用情景预设: 如果我之后想获取帮助，请你说'输入 !help 或 !帮助 获取帮助'
Traceback (most recent call last):
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 77, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/bot/plugins/revLibs/pkg/process/impls/edgegpt.py", line 51, in get_reply
    resp = asyncio.run(task)
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT.py", line 317, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT.py", line 267, in ask_stream
    self.request.update(prompt=prompt, conversation_style=conversation_style)
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT.py", line 147, in update
    conversation_style = getattr(ConversationStyle, conversation_style)
  File "/usr/local/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: harmonyv3
[2023-03-24 04:47:18.230] main.py (112) - [ERROR] : [rev] Traceback (most recent call last):
  File "/bot/plugins/revLibs/main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 58, in process_message
    raise e
  File "/bot/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/bot/plugins/revLibs/pkg/process/revss.py", line 77, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/bot/plugins/revLibs/pkg/process/impls/edgegpt.py", line 51, in get_reply
    resp = asyncio.run(task)
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT.py", line 317, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT.py", line 267, in ask_stream
    self.request.update(prompt=prompt, conversation_style=conversation_style)
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT.py", line 147, in update
    conversation_style = getattr(ConversationStyle, conversation_style)
  File "/usr/local/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: harmonyv3

**Comment by RockChinQ** [comment]
无法复现此问题，建议使用`!plugin update`更新逆向库插件，待完成后重启程序

**Comment by RockChinQ** [comment]
我的锅，写错了，请参考目前的`revcfg-template.py`文件中的`new_bing_style`字段在`revcfg.py`中进行更改
