### ISSUE TITLE
 Authentication failed. You have not been accepted into the beta.

### ISSUE THREAD

**Issue by o3oGekkou** [RockChinQ/revLibs#93]
### 任务

- 我已严格按照文档中的步骤操作
- 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：New Bing

实际情况是：
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/EdgeGPT.py", line 226, in __init__
    self.struct = response.json()
  File "/root/anaconda3/lib/python3.9/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/root/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/QChatGPT/plugins/revLibs/main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 41, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 34, in create_instance
    return EdgeGPTImpl(cookies_dict, revcfg.new_bing_style if hasattr(revcfg, "new_bing_style") else ConversationStyle.balanced), True, cookies_dict
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 38, in __init__
    self.chatbot = Chatbot(cookies=cookies)
  File "/root/anaconda3/lib/python3.9/site-packages/EdgeGPT.py", line 319, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy)
  File "/root/anaconda3/lib/python3.9/site-packages/EdgeGPT.py", line 230, in __init__
    raise Exception(
Exception: Authentication failed. You have not been accepted into the beta.
换了两个号，网页端是一切正常的，依旧能聊天，就逆向出了问题，服务器在美国

**Comment by RockChinQ** [comment]
> Exception: Authentication failed. You have not been accepted into the beta.

鉴权失败：你没有被允许进入beta测试

**Comment by RockChinQ** [comment]
重新检查cookie是否与具有资格的账户相匹配，重新配置插件

**Comment by RockChinQ** [comment]
#98
