### ISSUE TITLE
[BUG]Exception: Authentication failed

### ISSUE THREAD

**Issue by tHaxWLa** [RockChinQ/revLibs#96]
请您认真填写以下信息。

### 任务

- [x] 我已严格按照文档中的步骤操作
- [x] 我已经搜索了相关的issue

### 预期/正在使用的逆向库

我要使用的逆向库是：New Bing（例如：New Bing）

revLibs v0.4.0
revChatGPT 4.0.8
EdgeGPT 0.1.8

### 期望情况

我希望的情况是：

### 实际情况

实际情况是：
```
Status code: 302
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://cn.bing.com/edgesvc/turing/conversation/create">here</a>.</h2>
</body></html>

https://edgeservices.bing.com/edgesvc/turing/conversation/create
[2023-03-24 21:15:49.853] main.py (112) - [ERROR] : [rev] Traceback (most recent call last):
  File "/home/orangepi/act/zbing/QChatGPT/plugins/revLibs/main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/orangepi/act/zbing/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/home/orangepi/act/zbing/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 111, in get_session
    __sessions__[name] = RevSession(name)
  File "/home/orangepi/act/zbing/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 41, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "/home/orangepi/act/zbing/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 34, in create_instance
    return EdgeGPTImpl(cookies_dict, revcfg.new_bing_style if hasattr(revcfg, "new_bing_style") else ConversationStyle.balanced), True, cookies_dict
  File "/home/orangepi/act/zbing/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 38, in __init__
    self.chatbot = Chatbot(cookies=cookies)
  File "/home/orangepi/.local/lib/python3.9/site-packages/EdgeGPT.py", line 320, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy)
  File "/home/orangepi/.local/lib/python3.9/site-packages/EdgeGPT.py", line 225, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed
```
或许需要加入代理?

**Comment by RockChinQ** [comment]
#98，已修复，请使用!plugin update进行更新
